/* Carousel.c generated by valac 0.34.8, the Vala compiler
 * generated from Carousel.vala, do not modify */

/*
* Copyright (c) 2017 elementary LLC (https://elementary.io)
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define APP_CENTER_WIDGETS_TYPE_CAROUSEL (app_center_widgets_carousel_get_type ())
#define APP_CENTER_WIDGETS_CAROUSEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_CAROUSEL, AppCenterWidgetsCarousel))
#define APP_CENTER_WIDGETS_CAROUSEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_TYPE_CAROUSEL, AppCenterWidgetsCarouselClass))
#define APP_CENTER_WIDGETS_IS_CAROUSEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_CAROUSEL))
#define APP_CENTER_WIDGETS_IS_CAROUSEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_TYPE_CAROUSEL))
#define APP_CENTER_WIDGETS_CAROUSEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_TYPE_CAROUSEL, AppCenterWidgetsCarouselClass))

typedef struct _AppCenterWidgetsCarousel AppCenterWidgetsCarousel;
typedef struct _AppCenterWidgetsCarouselClass AppCenterWidgetsCarouselClass;
typedef struct _AppCenterWidgetsCarouselPrivate AppCenterWidgetsCarouselPrivate;

#define APP_CENTER_CORE_TYPE_PACKAGE (app_center_core_package_get_type ())
#define APP_CENTER_CORE_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackage))
#define APP_CENTER_CORE_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))
#define APP_CENTER_CORE_IS_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_IS_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_PACKAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))

typedef struct _AppCenterCorePackage AppCenterCorePackage;
typedef struct _AppCenterCorePackageClass AppCenterCorePackageClass;

#define APP_CENTER_WIDGETS_TYPE_CAROUSEL_ITEM (app_center_widgets_carousel_item_get_type ())
#define APP_CENTER_WIDGETS_CAROUSEL_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_CAROUSEL_ITEM, AppCenterWidgetsCarouselItem))
#define APP_CENTER_WIDGETS_CAROUSEL_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_TYPE_CAROUSEL_ITEM, AppCenterWidgetsCarouselItemClass))
#define APP_CENTER_WIDGETS_IS_CAROUSEL_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_CAROUSEL_ITEM))
#define APP_CENTER_WIDGETS_IS_CAROUSEL_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_TYPE_CAROUSEL_ITEM))
#define APP_CENTER_WIDGETS_CAROUSEL_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_TYPE_CAROUSEL_ITEM, AppCenterWidgetsCarouselItemClass))

typedef struct _AppCenterWidgetsCarouselItem AppCenterWidgetsCarouselItem;
typedef struct _AppCenterWidgetsCarouselItemClass AppCenterWidgetsCarouselItemClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AppCenterWidgetsCarousel {
	GtkFlowBox parent_instance;
	AppCenterWidgetsCarouselPrivate * priv;
};

struct _AppCenterWidgetsCarouselClass {
	GtkFlowBoxClass parent_class;
};


static gpointer app_center_widgets_carousel_parent_class = NULL;

GType app_center_widgets_carousel_get_type (void) G_GNUC_CONST;
enum  {
	APP_CENTER_WIDGETS_CAROUSEL_DUMMY_PROPERTY
};
AppCenterWidgetsCarousel* app_center_widgets_carousel_new (void);
AppCenterWidgetsCarousel* app_center_widgets_carousel_construct (GType object_type);
GType app_center_core_package_get_type (void) G_GNUC_CONST;
void app_center_widgets_carousel_add_package (AppCenterWidgetsCarousel* self, AppCenterCorePackage* package);
GType app_center_widgets_carousel_item_get_type (void) G_GNUC_CONST;
AppCenterWidgetsCarouselItem* app_center_widgets_carousel_item_new (AppCenterCorePackage* package);
AppCenterWidgetsCarouselItem* app_center_widgets_carousel_item_construct (GType object_type, AppCenterCorePackage* package);


AppCenterWidgetsCarousel* app_center_widgets_carousel_construct (GType object_type) {
	AppCenterWidgetsCarousel * self = NULL;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	self = (AppCenterWidgetsCarousel*) g_object_new (object_type, "activate-on-single-click", TRUE, "column-spacing", 12, "row-spacing", 12, "hexpand", TRUE, "homogeneous", TRUE, "max-children-per-line", 5, "min-children-per-line", 2, NULL);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	return self;
#line 92 "Carousel.c"
}


AppCenterWidgetsCarousel* app_center_widgets_carousel_new (void) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	return app_center_widgets_carousel_construct (APP_CENTER_WIDGETS_TYPE_CAROUSEL);
#line 99 "Carousel.c"
}


void app_center_widgets_carousel_add_package (AppCenterWidgetsCarousel* self, AppCenterCorePackage* package) {
	AppCenterWidgetsCarouselItem* carousel_item = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	AppCenterWidgetsCarouselItem* _tmp1_ = NULL;
#line 31 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	g_return_if_fail (self != NULL);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	_tmp0_ = package;
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	_tmp1_ = app_center_widgets_carousel_item_new (_tmp0_);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	g_object_ref_sink (_tmp1_);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	carousel_item = _tmp1_;
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) carousel_item);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 31 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	_g_object_unref0 (carousel_item);
#line 123 "Carousel.c"
}


static void app_center_widgets_carousel_class_init (AppCenterWidgetsCarouselClass * klass) {
#line 20 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Carousel/Carousel.vala"
	app_center_widgets_carousel_parent_class = g_type_class_peek_parent (klass);
#line 130 "Carousel.c"
}


static void app_center_widgets_carousel_instance_init (AppCenterWidgetsCarousel * self) {
}


GType app_center_widgets_carousel_get_type (void) {
	static volatile gsize app_center_widgets_carousel_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_widgets_carousel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterWidgetsCarouselClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_widgets_carousel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterWidgetsCarousel), 0, (GInstanceInitFunc) app_center_widgets_carousel_instance_init, NULL };
		GType app_center_widgets_carousel_type_id;
		app_center_widgets_carousel_type_id = g_type_register_static (gtk_flow_box_get_type (), "AppCenterWidgetsCarousel", &g_define_type_info, 0);
		g_once_init_leave (&app_center_widgets_carousel_type_id__volatile, app_center_widgets_carousel_type_id);
	}
	return app_center_widgets_carousel_type_id__volatile;
}



