/* ChangeInformation.c generated by valac 0.34.8, the Vala compiler
 * generated from ChangeInformation.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2014-2016 elementary LLC. (https://elementary.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: Corentin Noël <corentin@elementary.io>
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <packagekit-glib2/packagekit.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>


#define APP_CENTER_CORE_TYPE_CHANGE_INFORMATION (app_center_core_change_information_get_type ())
#define APP_CENTER_CORE_CHANGE_INFORMATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformation))
#define APP_CENTER_CORE_CHANGE_INFORMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformationClass))
#define APP_CENTER_CORE_IS_CHANGE_INFORMATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION))
#define APP_CENTER_CORE_IS_CHANGE_INFORMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION))
#define APP_CENTER_CORE_CHANGE_INFORMATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformationClass))

typedef struct _AppCenterCoreChangeInformation AppCenterCoreChangeInformation;
typedef struct _AppCenterCoreChangeInformationClass AppCenterCoreChangeInformationClass;
typedef struct _AppCenterCoreChangeInformationPrivate AppCenterCoreChangeInformationPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AppCenterCoreChangeInformation {
	GObject parent_instance;
	AppCenterCoreChangeInformationPrivate * priv;
};

struct _AppCenterCoreChangeInformationClass {
	GObjectClass parent_class;
};

struct _AppCenterCoreChangeInformationPrivate {
	GeeTreeSet* _changes;
	GeeTreeSet* _details;
	gboolean _can_cancel;
	PkStatusEnum _status;
	gdouble _progress;
	gint current_progress;
	gint last_progress;
	PkStatusEnum current_status;
	gdouble progress_denom;
};


static gpointer app_center_core_change_information_parent_class = NULL;

GType app_center_core_change_information_get_type (void) G_GNUC_CONST;
#define APP_CENTER_CORE_CHANGE_INFORMATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformationPrivate))
enum  {
	APP_CENTER_CORE_CHANGE_INFORMATION_DUMMY_PROPERTY,
	APP_CENTER_CORE_CHANGE_INFORMATION_CHANGES,
	APP_CENTER_CORE_CHANGE_INFORMATION_DETAILS,
	APP_CENTER_CORE_CHANGE_INFORMATION_CAN_CANCEL,
	APP_CENTER_CORE_CHANGE_INFORMATION_STATUS,
	APP_CENTER_CORE_CHANGE_INFORMATION_PROGRESS
};
gboolean app_center_core_change_information_has_changes (AppCenterCoreChangeInformation* self);
GeeTreeSet* app_center_core_change_information_get_changes (AppCenterCoreChangeInformation* self);
gchar* app_center_core_change_information_get_status_string (AppCenterCoreChangeInformation* self);
PkStatusEnum app_center_core_change_information_get_status (AppCenterCoreChangeInformation* self);
guint64 app_center_core_change_information_get_size (AppCenterCoreChangeInformation* self);
GeeTreeSet* app_center_core_change_information_get_details (AppCenterCoreChangeInformation* self);
void app_center_core_change_information_start (AppCenterCoreChangeInformation* self);
static void app_center_core_change_information_set_progress (AppCenterCoreChangeInformation* self, gdouble value);
static void app_center_core_change_information_set_status (AppCenterCoreChangeInformation* self, PkStatusEnum value);
void app_center_core_change_information_complete (AppCenterCoreChangeInformation* self);
void app_center_core_change_information_reset_progress (AppCenterCoreChangeInformation* self);
void app_center_core_change_information_cancel (AppCenterCoreChangeInformation* self);
void app_center_core_change_information_clear_update_info (AppCenterCoreChangeInformation* self);
void app_center_core_change_information_ProgressCallback (AppCenterCoreChangeInformation* self, PkProgress* progress, PkProgressType type);
static void app_center_core_change_information_set_can_cancel (AppCenterCoreChangeInformation* self, gboolean value);
AppCenterCoreChangeInformation* app_center_core_change_information_new (void);
AppCenterCoreChangeInformation* app_center_core_change_information_construct (GType object_type);
static void app_center_core_change_information_set_changes (AppCenterCoreChangeInformation* self, GeeTreeSet* value);
static void app_center_core_change_information_set_details (AppCenterCoreChangeInformation* self, GeeTreeSet* value);
gboolean app_center_core_change_information_get_can_cancel (AppCenterCoreChangeInformation* self);
gdouble app_center_core_change_information_get_progress (AppCenterCoreChangeInformation* self);
static GObject * app_center_core_change_information_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void app_center_core_change_information_finalize (GObject* obj);
static void _vala_app_center_core_change_information_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_app_center_core_change_information_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


gboolean app_center_core_change_information_has_changes (AppCenterCoreChangeInformation* self) {
	gboolean result = FALSE;
	GeeTreeSet* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_changes;
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp1_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp0_);
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp2_ = _tmp1_;
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = _tmp2_ > 0;
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 126 "ChangeInformation.c"
}


gchar* app_center_core_change_information_get_status_string (AppCenterCoreChangeInformation* self) {
	gchar* result = NULL;
	PkStatusEnum _tmp0_ = 0;
#line 51 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_status;
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	switch (_tmp0_) {
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_SETUP:
#line 141 "ChangeInformation.c"
		{
			const gchar* _tmp1_ = NULL;
			gchar* _tmp2_ = NULL;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp1_ = _ ("Starting");
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp2_ = g_strdup (_tmp1_);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp2_;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 153 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_WAIT:
#line 157 "ChangeInformation.c"
		{
			const gchar* _tmp3_ = NULL;
			gchar* _tmp4_ = NULL;
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp3_ = _ ("Waiting");
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp4_ = g_strdup (_tmp3_);
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp4_;
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 169 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_RUNNING:
#line 173 "ChangeInformation.c"
		{
			const gchar* _tmp5_ = NULL;
			gchar* _tmp6_ = NULL;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp5_ = _ ("Running");
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp6_ = g_strdup (_tmp5_);
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp6_;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 185 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_QUERY:
#line 189 "ChangeInformation.c"
		{
			const gchar* _tmp7_ = NULL;
			gchar* _tmp8_ = NULL;
#line 60 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp7_ = _ ("Querying");
#line 60 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp8_ = g_strdup (_tmp7_);
#line 60 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp8_;
#line 60 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 201 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_INFO:
#line 205 "ChangeInformation.c"
		{
			const gchar* _tmp9_ = NULL;
			gchar* _tmp10_ = NULL;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp9_ = _ ("Getting information");
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp10_ = g_strdup (_tmp9_);
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp10_;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 217 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_REMOVE:
#line 221 "ChangeInformation.c"
		{
			const gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp11_ = _ ("Removing packages");
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp12_ = g_strdup (_tmp11_);
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp12_;
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 233 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD:
#line 237 "ChangeInformation.c"
		{
			const gchar* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp13_ = _ ("Downloading");
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp14_ = g_strdup (_tmp13_);
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp14_;
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 249 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_INSTALL:
#line 253 "ChangeInformation.c"
		{
			const gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp15_ = _ ("Installing");
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp16_ = g_strdup (_tmp15_);
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp16_;
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 265 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_REFRESH_CACHE:
#line 269 "ChangeInformation.c"
		{
			const gchar* _tmp17_ = NULL;
			gchar* _tmp18_ = NULL;
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp17_ = _ ("Refreshing software list");
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp18_ = g_strdup (_tmp17_);
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp18_;
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 281 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_UPDATE:
#line 285 "ChangeInformation.c"
		{
			const gchar* _tmp19_ = NULL;
			gchar* _tmp20_ = NULL;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp19_ = _ ("Installing updates");
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp20_ = g_strdup (_tmp19_);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp20_;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 297 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_CLEANUP:
#line 301 "ChangeInformation.c"
		{
			const gchar* _tmp21_ = NULL;
			gchar* _tmp22_ = NULL;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp21_ = _ ("Cleaning up packages");
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp22_ = g_strdup (_tmp21_);
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp22_;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 313 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_OBSOLETE:
#line 317 "ChangeInformation.c"
		{
			const gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp23_ = _ ("Obsoleting packages");
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp24_ = g_strdup (_tmp23_);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp24_;
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 329 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DEP_RESOLVE:
#line 333 "ChangeInformation.c"
		{
			const gchar* _tmp25_ = NULL;
			gchar* _tmp26_ = NULL;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp25_ = _ ("Resolving dependencies");
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp26_ = g_strdup (_tmp25_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp26_;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 345 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_SIG_CHECK:
#line 349 "ChangeInformation.c"
		{
			const gchar* _tmp27_ = NULL;
			gchar* _tmp28_ = NULL;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp27_ = _ ("Checking signatures");
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp28_ = g_strdup (_tmp27_);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp28_;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 361 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_TEST_COMMIT:
#line 365 "ChangeInformation.c"
		{
			const gchar* _tmp29_ = NULL;
			gchar* _tmp30_ = NULL;
#line 82 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp29_ = _ ("Testing changes");
#line 82 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp30_ = g_strdup (_tmp29_);
#line 82 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp30_;
#line 82 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 377 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_COMMIT:
#line 381 "ChangeInformation.c"
		{
			const gchar* _tmp31_ = NULL;
			gchar* _tmp32_ = NULL;
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp31_ = _ ("Committing changes");
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp32_ = g_strdup (_tmp31_);
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp32_;
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 393 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_REQUEST:
#line 397 "ChangeInformation.c"
		{
			const gchar* _tmp33_ = NULL;
			gchar* _tmp34_ = NULL;
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp33_ = _ ("Requesting data");
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp34_ = g_strdup (_tmp33_);
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp34_;
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 409 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_FINISHED:
#line 413 "ChangeInformation.c"
		{
			const gchar* _tmp35_ = NULL;
			gchar* _tmp36_ = NULL;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp35_ = _ ("Finished");
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp36_ = g_strdup (_tmp35_);
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp36_;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 425 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_CANCEL:
#line 429 "ChangeInformation.c"
		{
			const gchar* _tmp37_ = NULL;
			gchar* _tmp38_ = NULL;
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp37_ = _ ("Cancelling");
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp38_ = g_strdup (_tmp37_);
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp38_;
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 441 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD_REPOSITORY:
#line 445 "ChangeInformation.c"
		{
			const gchar* _tmp39_ = NULL;
			gchar* _tmp40_ = NULL;
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp39_ = _ ("Downloading repository information");
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp40_ = g_strdup (_tmp39_);
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp40_;
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 457 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD_PACKAGELIST:
#line 461 "ChangeInformation.c"
		{
			const gchar* _tmp41_ = NULL;
			gchar* _tmp42_ = NULL;
#line 94 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp41_ = _ ("Downloading list of packages");
#line 94 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp42_ = g_strdup (_tmp41_);
#line 94 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp42_;
#line 94 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 473 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD_FILELIST:
#line 477 "ChangeInformation.c"
		{
			const gchar* _tmp43_ = NULL;
			gchar* _tmp44_ = NULL;
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp43_ = _ ("Downloading file lists");
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp44_ = g_strdup (_tmp43_);
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp44_;
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 489 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD_CHANGELOG:
#line 493 "ChangeInformation.c"
		{
			const gchar* _tmp45_ = NULL;
			gchar* _tmp46_ = NULL;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp45_ = _ ("Downloading lists of changes");
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp46_ = g_strdup (_tmp45_);
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp46_;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 505 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD_GROUP:
#line 509 "ChangeInformation.c"
		{
			const gchar* _tmp47_ = NULL;
			gchar* _tmp48_ = NULL;
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp47_ = _ ("Downloading groups");
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp48_ = g_strdup (_tmp47_);
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp48_;
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 521 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_DOWNLOAD_UPDATEINFO:
#line 525 "ChangeInformation.c"
		{
			const gchar* _tmp49_ = NULL;
			gchar* _tmp50_ = NULL;
#line 102 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp49_ = _ ("Downloading update information");
#line 102 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp50_ = g_strdup (_tmp49_);
#line 102 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp50_;
#line 102 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 537 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_REPACKAGING:
#line 541 "ChangeInformation.c"
		{
			const gchar* _tmp51_ = NULL;
			gchar* _tmp52_ = NULL;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp51_ = _ ("Repackaging files");
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp52_ = g_strdup (_tmp51_);
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp52_;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 553 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_LOADING_CACHE:
#line 557 "ChangeInformation.c"
		{
			const gchar* _tmp53_ = NULL;
			gchar* _tmp54_ = NULL;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp53_ = _ ("Loading cache");
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp54_ = g_strdup (_tmp53_);
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp54_;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 569 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_SCAN_APPLICATIONS:
#line 573 "ChangeInformation.c"
		{
			const gchar* _tmp55_ = NULL;
			gchar* _tmp56_ = NULL;
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp55_ = _ ("Scanning applications");
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp56_ = g_strdup (_tmp55_);
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp56_;
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 585 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_GENERATE_PACKAGE_LIST:
#line 589 "ChangeInformation.c"
		{
			const gchar* _tmp57_ = NULL;
			gchar* _tmp58_ = NULL;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp57_ = _ ("Generating package lists");
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp58_ = g_strdup (_tmp57_);
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp58_;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 601 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_WAITING_FOR_LOCK:
#line 605 "ChangeInformation.c"
		{
			const gchar* _tmp59_ = NULL;
			gchar* _tmp60_ = NULL;
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp59_ = _ ("Waiting for package manager lock");
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp60_ = g_strdup (_tmp59_);
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp60_;
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 617 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_WAITING_FOR_AUTH:
#line 621 "ChangeInformation.c"
		{
			const gchar* _tmp61_ = NULL;
			gchar* _tmp62_ = NULL;
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp61_ = _ ("Waiting for authentication");
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp62_ = g_strdup (_tmp61_);
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp62_;
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 633 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_SCAN_PROCESS_LIST:
#line 637 "ChangeInformation.c"
		{
			const gchar* _tmp63_ = NULL;
			gchar* _tmp64_ = NULL;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp63_ = _ ("Updating running applications");
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp64_ = g_strdup (_tmp63_);
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp64_;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 649 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_CHECK_EXECUTABLE_FILES:
#line 653 "ChangeInformation.c"
		{
			const gchar* _tmp65_ = NULL;
			gchar* _tmp66_ = NULL;
#line 118 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp65_ = _ ("Checking applications in use");
#line 118 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp66_ = g_strdup (_tmp65_);
#line 118 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp66_;
#line 118 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 665 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_CHECK_LIBRARIES:
#line 669 "ChangeInformation.c"
		{
			const gchar* _tmp67_ = NULL;
			gchar* _tmp68_ = NULL;
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp67_ = _ ("Checking libraries in use");
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp68_ = g_strdup (_tmp67_);
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp68_;
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 681 "ChangeInformation.c"
		}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_STATUS_ENUM_COPY_FILES:
#line 685 "ChangeInformation.c"
		{
			const gchar* _tmp69_ = NULL;
			gchar* _tmp70_ = NULL;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp69_ = _ ("Copying files");
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp70_ = g_strdup (_tmp69_);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp70_;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 697 "ChangeInformation.c"
		}
		default:
		{
			const gchar* _tmp71_ = NULL;
			gchar* _tmp72_ = NULL;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp71_ = _ ("Unknown state");
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp72_ = g_strdup (_tmp71_);
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			result = _tmp72_;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			return result;
#line 711 "ChangeInformation.c"
		}
	}
}


guint64 app_center_core_change_information_get_size (AppCenterCoreChangeInformation* self) {
	guint64 result = 0ULL;
	guint64 size = 0ULL;
#line 128 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, 0ULL);
#line 129 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	size = 0ULL;
#line 724 "ChangeInformation.c"
	{
		GeeIterator* _detail_it = NULL;
		GeeTreeSet* _tmp0_ = NULL;
		GeeIterator* _tmp1_ = NULL;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		_tmp0_ = self->priv->_details;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		_tmp1_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) _tmp0_);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		_detail_it = _tmp1_;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		while (TRUE) {
#line 737 "ChangeInformation.c"
			GeeIterator* _tmp2_ = NULL;
			gboolean _tmp3_ = FALSE;
			PkDetails* detail = NULL;
			GeeIterator* _tmp4_ = NULL;
			gpointer _tmp5_ = NULL;
			guint64 _tmp6_ = 0ULL;
			PkDetails* _tmp7_ = NULL;
			guint64 _tmp8_ = 0ULL;
			guint64 _tmp9_ = 0ULL;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp2_ = _detail_it;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp3_ = gee_iterator_next (_tmp2_);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			if (!_tmp3_) {
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				break;
#line 755 "ChangeInformation.c"
			}
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp4_ = _detail_it;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp5_ = gee_iterator_get (_tmp4_);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			detail = (PkDetails*) _tmp5_;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp6_ = size;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp7_ = detail;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			g_object_get (_tmp7_, "size", &_tmp8_, NULL);
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp9_ = _tmp8_;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			size = _tmp6_ + _tmp9_;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_g_object_unref0 (detail);
#line 775 "ChangeInformation.c"
		}
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		_g_object_unref0 (_detail_it);
#line 779 "ChangeInformation.c"
	}
#line 134 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = size;
#line 134 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 785 "ChangeInformation.c"
}


void app_center_core_change_information_start (AppCenterCoreChangeInformation* self) {
#line 137 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_progress (self, (gdouble) 0.0f);
#line 139 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_emit_by_name (self, "progress-changed");
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_status (self, PK_STATUS_ENUM_WAIT);
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_emit_by_name (self, "status-changed");
#line 800 "ChangeInformation.c"
}


void app_center_core_change_information_complete (AppCenterCoreChangeInformation* self) {
#line 144 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 145 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_status (self, PK_STATUS_ENUM_FINISHED);
#line 146 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_emit_by_name (self, "status-changed");
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_reset_progress (self);
#line 813 "ChangeInformation.c"
}


void app_center_core_change_information_cancel (AppCenterCoreChangeInformation* self) {
#line 150 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 151 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_progress (self, (gdouble) 0.0f);
#line 152 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_emit_by_name (self, "progress-changed");
#line 153 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_status (self, PK_STATUS_ENUM_CANCEL);
#line 154 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_emit_by_name (self, "status-changed");
#line 155 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_reset_progress (self);
#line 830 "ChangeInformation.c"
}


void app_center_core_change_information_clear_update_info (AppCenterCoreChangeInformation* self) {
	GeeTreeSet* _tmp0_ = NULL;
	GeeTreeSet* _tmp1_ = NULL;
#line 158 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 159 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_changes;
#line 159 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp0_);
#line 160 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp1_ = self->priv->_details;
#line 160 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp1_);
#line 847 "ChangeInformation.c"
}


void app_center_core_change_information_reset_progress (AppCenterCoreChangeInformation* self) {
#line 163 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 164 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_status (self, PK_STATUS_ENUM_SETUP);
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_progress (self, (gdouble) 0.0f);
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->last_progress = 0;
#line 167 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->current_progress = 0;
#line 168 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->current_status = 0;
#line 169 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->progress_denom = (gdouble) 200.0f;
#line 866 "ChangeInformation.c"
}


void app_center_core_change_information_ProgressCallback (AppCenterCoreChangeInformation* self, PkProgress* progress, PkProgressType type) {
	PkProgressType _tmp0_ = 0;
#line 172 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 172 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (progress != NULL);
#line 173 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = type;
#line 173 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	switch (_tmp0_) {
#line 173 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_PROGRESS_TYPE_ALLOW_CANCEL:
#line 882 "ChangeInformation.c"
		{
			PkProgress* _tmp1_ = NULL;
			gboolean _tmp2_ = FALSE;
			gboolean _tmp3_ = FALSE;
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp1_ = progress;
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			g_object_get (_tmp1_, "allow-cancel", &_tmp2_, NULL);
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp3_ = _tmp2_;
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			app_center_core_change_information_set_can_cancel (self, _tmp3_);
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			break;
#line 897 "ChangeInformation.c"
		}
#line 173 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_PROGRESS_TYPE_ITEM_PROGRESS:
#line 901 "ChangeInformation.c"
		{
			PkStatusEnum _tmp4_ = 0;
			PkProgress* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			gint _tmp19_ = 0;
			gdouble progress_sum = 0.0;
			gint _tmp20_ = 0;
			gint _tmp21_ = 0;
			gdouble _tmp22_ = 0.0;
			gdouble _tmp23_ = 0.0;
#line 178 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp4_ = self->priv->current_status;
#line 178 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			if (_tmp4_ == PK_STATUS_ENUM_SETUP) {
#line 916 "ChangeInformation.c"
				PkProgress* _tmp5_ = NULL;
				guint _tmp6_ = 0U;
				guint _tmp7_ = 0U;
				PkStatusEnum _tmp8_ = 0;
#line 179 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				_tmp5_ = progress;
#line 179 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				g_object_get (_tmp5_, "status", &_tmp6_, NULL);
#line 179 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				_tmp7_ = _tmp6_;
#line 179 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				self->priv->current_status = (PkStatusEnum) _tmp7_;
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				_tmp8_ = self->priv->current_status;
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				if (_tmp8_ != PK_STATUS_ENUM_DOWNLOAD) {
#line 182 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					self->priv->progress_denom = (gdouble) 100.0f;
#line 935 "ChangeInformation.c"
				}
			} else {
				PkProgress* _tmp9_ = NULL;
				guint _tmp10_ = 0U;
				guint _tmp11_ = 0U;
				PkStatusEnum _tmp12_ = 0;
#line 186 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				_tmp9_ = progress;
#line 186 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				g_object_get (_tmp9_, "status", &_tmp10_, NULL);
#line 186 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				_tmp11_ = _tmp10_;
#line 186 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				_tmp12_ = self->priv->current_status;
#line 186 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
				if (((PkStatusEnum) _tmp11_) != _tmp12_) {
#line 952 "ChangeInformation.c"
					PkProgress* _tmp13_ = NULL;
					guint _tmp14_ = 0U;
					guint _tmp15_ = 0U;
					gint _tmp16_ = 0;
#line 187 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					_tmp13_ = progress;
#line 187 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					g_object_get (_tmp13_, "status", &_tmp14_, NULL);
#line 187 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					_tmp15_ = _tmp14_;
#line 187 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					self->priv->current_status = (PkStatusEnum) _tmp15_;
#line 188 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					_tmp16_ = self->priv->last_progress;
#line 188 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
					self->priv->current_progress = _tmp16_;
#line 969 "ChangeInformation.c"
				}
			}
#line 191 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp17_ = progress;
#line 191 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			g_object_get (_tmp17_, "percentage", &_tmp18_, NULL);
#line 191 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp19_ = _tmp18_;
#line 191 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			self->priv->last_progress = _tmp19_;
#line 192 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp20_ = self->priv->current_progress;
#line 192 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp21_ = self->priv->last_progress;
#line 192 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			progress_sum = (gdouble) (_tmp20_ + _tmp21_);
#line 193 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp22_ = progress_sum;
#line 193 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp23_ = self->priv->progress_denom;
#line 193 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			app_center_core_change_information_set_progress (self, _tmp22_ / _tmp23_);
#line 194 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			g_signal_emit_by_name (self, "progress-changed");
#line 195 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			break;
#line 996 "ChangeInformation.c"
		}
#line 173 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case PK_PROGRESS_TYPE_STATUS:
#line 1000 "ChangeInformation.c"
		{
			PkProgress* _tmp24_ = NULL;
			guint _tmp25_ = 0U;
			guint _tmp26_ = 0U;
#line 197 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp24_ = progress;
#line 197 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			g_object_get (_tmp24_, "status", &_tmp25_, NULL);
#line 197 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			_tmp26_ = _tmp25_;
#line 197 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			app_center_core_change_information_set_status (self, (PkStatusEnum) _tmp26_);
#line 198 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			g_signal_emit_by_name (self, "status-changed");
#line 199 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
			break;
#line 1017 "ChangeInformation.c"
		}
		default:
#line 173 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 1022 "ChangeInformation.c"
	}
}


AppCenterCoreChangeInformation* app_center_core_change_information_construct (GType object_type) {
	AppCenterCoreChangeInformation * self = NULL;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self = (AppCenterCoreChangeInformation*) g_object_new (object_type, NULL);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return self;
#line 1033 "ChangeInformation.c"
}


AppCenterCoreChangeInformation* app_center_core_change_information_new (void) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return app_center_core_change_information_construct (APP_CENTER_CORE_TYPE_CHANGE_INFORMATION);
#line 1040 "ChangeInformation.c"
}


GeeTreeSet* app_center_core_change_information_get_changes (AppCenterCoreChangeInformation* self) {
	GeeTreeSet* result;
	GeeTreeSet* _tmp0_ = NULL;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_changes;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = _tmp0_;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 1055 "ChangeInformation.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return self ? g_object_ref (self) : NULL;
#line 1062 "ChangeInformation.c"
}


static void app_center_core_change_information_set_changes (AppCenterCoreChangeInformation* self, GeeTreeSet* value) {
	GeeTreeSet* _tmp0_ = NULL;
	GeeTreeSet* _tmp1_ = NULL;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = value;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_g_object_unref0 (self->priv->_changes);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->_changes = _tmp1_;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_notify ((GObject *) self, "changes");
#line 1081 "ChangeInformation.c"
}


GeeTreeSet* app_center_core_change_information_get_details (AppCenterCoreChangeInformation* self) {
	GeeTreeSet* result;
	GeeTreeSet* _tmp0_ = NULL;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_details;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = _tmp0_;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 1096 "ChangeInformation.c"
}


static void app_center_core_change_information_set_details (AppCenterCoreChangeInformation* self, GeeTreeSet* value) {
	GeeTreeSet* _tmp0_ = NULL;
	GeeTreeSet* _tmp1_ = NULL;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = value;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_g_object_unref0 (self->priv->_details);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->_details = _tmp1_;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_notify ((GObject *) self, "details");
#line 1115 "ChangeInformation.c"
}


gboolean app_center_core_change_information_get_can_cancel (AppCenterCoreChangeInformation* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_can_cancel;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = _tmp0_;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 1130 "ChangeInformation.c"
}


static void app_center_core_change_information_set_can_cancel (AppCenterCoreChangeInformation* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = value;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->_can_cancel = _tmp0_;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_notify ((GObject *) self, "can-cancel");
#line 1144 "ChangeInformation.c"
}


PkStatusEnum app_center_core_change_information_get_status (AppCenterCoreChangeInformation* self) {
	PkStatusEnum result;
	PkStatusEnum _tmp0_ = 0;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_status;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = _tmp0_;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 1159 "ChangeInformation.c"
}


static void app_center_core_change_information_set_status (AppCenterCoreChangeInformation* self, PkStatusEnum value) {
	PkStatusEnum _tmp0_ = 0;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = value;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->_status = _tmp0_;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_notify ((GObject *) self, "status");
#line 1173 "ChangeInformation.c"
}


gdouble app_center_core_change_information_get_progress (AppCenterCoreChangeInformation* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = self->priv->_progress;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	result = _tmp0_;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return result;
#line 1188 "ChangeInformation.c"
}


static void app_center_core_change_information_set_progress (AppCenterCoreChangeInformation* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_return_if_fail (self != NULL);
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = value;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->_progress = _tmp0_;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_notify ((GObject *) self, "progress");
#line 1202 "ChangeInformation.c"
}


static GObject * app_center_core_change_information_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterCoreChangeInformation * self;
	GeeTreeSet* _tmp0_ = NULL;
	GeeTreeSet* _tmp1_ = NULL;
	GeeTreeSet* _tmp2_ = NULL;
	GeeTreeSet* _tmp3_ = NULL;
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	parent_class = G_OBJECT_CLASS (app_center_core_change_information_parent_class);
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformation);
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp0_ = gee_tree_set_new (pk_package_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp1_ = _tmp0_;
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_changes (self, _tmp1_);
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_g_object_unref0 (_tmp1_);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp2_ = gee_tree_set_new (pk_details_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_tmp3_ = _tmp2_;
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_details (self, _tmp3_);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_g_object_unref0 (_tmp3_);
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_status (self, PK_STATUS_ENUM_SETUP);
#line 39 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_set_progress (self, (gdouble) 0.0f);
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->current_progress = 0;
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->last_progress = 0;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->current_status = PK_STATUS_ENUM_SETUP;
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->progress_denom = (gdouble) 200.0f;
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	return obj;
#line 1250 "ChangeInformation.c"
}


static void app_center_core_change_information_class_init (AppCenterCoreChangeInformationClass * klass) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	app_center_core_change_information_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_type_class_add_private (klass, sizeof (AppCenterCoreChangeInformationPrivate));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_app_center_core_change_information_get_property;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_app_center_core_change_information_set_property;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_core_change_information_constructor;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	G_OBJECT_CLASS (klass)->finalize = app_center_core_change_information_finalize;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CENTER_CORE_CHANGE_INFORMATION_CHANGES, g_param_spec_object ("changes", "changes", "changes", GEE_TYPE_TREE_SET, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CENTER_CORE_CHANGE_INFORMATION_DETAILS, g_param_spec_object ("details", "details", "details", GEE_TYPE_TREE_SET, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CENTER_CORE_CHANGE_INFORMATION_CAN_CANCEL, g_param_spec_boolean ("can-cancel", "can-cancel", "can-cancel", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CENTER_CORE_CHANGE_INFORMATION_STATUS, g_param_spec_enum ("status", "status", "status", pk_status_enum_get_type (), 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CENTER_CORE_CHANGE_INFORMATION_PROGRESS, g_param_spec_double ("progress", "progress", "progress", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_new ("status_changed", APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	g_signal_new ("progress_changed", APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1281 "ChangeInformation.c"
}


static void app_center_core_change_information_instance_init (AppCenterCoreChangeInformation * self) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv = APP_CENTER_CORE_CHANGE_INFORMATION_GET_PRIVATE (self);
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self->priv->_can_cancel = TRUE;
#line 1290 "ChangeInformation.c"
}


static void app_center_core_change_information_finalize (GObject* obj) {
	AppCenterCoreChangeInformation * self;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformation);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_g_object_unref0 (self->priv->_changes);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	_g_object_unref0 (self->priv->_details);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	G_OBJECT_CLASS (app_center_core_change_information_parent_class)->finalize (obj);
#line 1304 "ChangeInformation.c"
}


GType app_center_core_change_information_get_type (void) {
	static volatile gsize app_center_core_change_information_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_core_change_information_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterCoreChangeInformationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_core_change_information_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterCoreChangeInformation), 0, (GInstanceInitFunc) app_center_core_change_information_instance_init, NULL };
		GType app_center_core_change_information_type_id;
		app_center_core_change_information_type_id = g_type_register_static (G_TYPE_OBJECT, "AppCenterCoreChangeInformation", &g_define_type_info, 0);
		g_once_init_leave (&app_center_core_change_information_type_id__volatile, app_center_core_change_information_type_id);
	}
	return app_center_core_change_information_type_id__volatile;
}


static void _vala_app_center_core_change_information_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AppCenterCoreChangeInformation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformation);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	switch (property_id) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_CHANGES:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		g_value_set_object (value, app_center_core_change_information_get_changes (self));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_DETAILS:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		g_value_set_object (value, app_center_core_change_information_get_details (self));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_CAN_CANCEL:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		g_value_set_boolean (value, app_center_core_change_information_get_can_cancel (self));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_STATUS:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		g_value_set_enum (value, app_center_core_change_information_get_status (self));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_PROGRESS:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		g_value_set_double (value, app_center_core_change_information_get_progress (self));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 1355 "ChangeInformation.c"
		default:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 1361 "ChangeInformation.c"
	}
}


static void _vala_app_center_core_change_information_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	AppCenterCoreChangeInformation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformation);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
	switch (property_id) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_CHANGES:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		app_center_core_change_information_set_changes (self, g_value_get_object (value));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_DETAILS:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		app_center_core_change_information_set_details (self, g_value_get_object (value));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_CAN_CANCEL:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		app_center_core_change_information_set_can_cancel (self, g_value_get_boolean (value));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_STATUS:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		app_center_core_change_information_set_status (self, g_value_get_enum (value));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		case APP_CENTER_CORE_CHANGE_INFORMATION_PROGRESS:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		app_center_core_change_information_set_progress (self, g_value_get_double (value));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 1401 "ChangeInformation.c"
		default:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Core/ChangeInformation.vala"
		break;
#line 1407 "ChangeInformation.c"
	}
}



