/* Application.c generated by valac 0.34.8, the Vala compiler
 * generated from Application.vala, do not modify */

/* Copyright 2015 Marvin Beckers <beckersmarvin@gmail.com>
*
* This program is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <packagekit-glib2/packagekit.h>
#include <locale.h>
#include <gio/gdesktopappinfo.h>


#define APP_CENTER_TYPE_APP (app_center_app_get_type ())
#define APP_CENTER_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_TYPE_APP, AppCenterApp))
#define APP_CENTER_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_TYPE_APP, AppCenterAppClass))
#define APP_CENTER_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_TYPE_APP))
#define APP_CENTER_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_TYPE_APP))
#define APP_CENTER_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_TYPE_APP, AppCenterAppClass))

typedef struct _AppCenterApp AppCenterApp;
typedef struct _AppCenterAppClass AppCenterAppClass;
typedef struct _AppCenterAppPrivate AppCenterAppPrivate;

#define APP_CENTER_TYPE_MAIN_WINDOW (app_center_main_window_get_type ())
#define APP_CENTER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_TYPE_MAIN_WINDOW, AppCenterMainWindow))
#define APP_CENTER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_TYPE_MAIN_WINDOW, AppCenterMainWindowClass))
#define APP_CENTER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_TYPE_MAIN_WINDOW))
#define APP_CENTER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_TYPE_MAIN_WINDOW))
#define APP_CENTER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_TYPE_MAIN_WINDOW, AppCenterMainWindowClass))

typedef struct _AppCenterMainWindow AppCenterMainWindow;
typedef struct _AppCenterMainWindowClass AppCenterMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define APP_CENTER_CORE_TYPE_CLIENT (app_center_core_client_get_type ())
#define APP_CENTER_CORE_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_CLIENT, AppCenterCoreClient))
#define APP_CENTER_CORE_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_CLIENT, AppCenterCoreClientClass))
#define APP_CENTER_CORE_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_CLIENT))
#define APP_CENTER_CORE_IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_CLIENT))
#define APP_CENTER_CORE_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_CLIENT, AppCenterCoreClientClass))

typedef struct _AppCenterCoreClient AppCenterCoreClient;
typedef struct _AppCenterCoreClientClass AppCenterCoreClientClass;

#define APP_CENTER_CORE_TYPE_PACKAGE (app_center_core_package_get_type ())
#define APP_CENTER_CORE_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackage))
#define APP_CENTER_CORE_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))
#define APP_CENTER_CORE_IS_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_IS_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_PACKAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))

typedef struct _AppCenterCorePackage AppCenterCorePackage;
typedef struct _AppCenterCorePackageClass AppCenterCorePackageClass;
typedef struct _Block15Data Block15Data;

#define TYPE_DBUS_SERVER (dbus_server_get_type ())
#define DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DBUS_SERVER, DBusServer))
#define DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DBUS_SERVER, DBusServerClass))
#define IS_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DBUS_SERVER))
#define IS_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DBUS_SERVER))
#define DBUS_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DBUS_SERVER, DBusServerClass))

typedef struct _DBusServer DBusServer;
typedef struct _DBusServerClass DBusServerClass;
typedef struct _Block16Data Block16Data;

#define APP_CENTER_CORE_PACKAGE_TYPE_STATE (app_center_core_package_state_get_type ())

#define APP_CENTER_TYPE_MESSAGE_DIALOG (app_center_message_dialog_get_type ())
#define APP_CENTER_MESSAGE_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_TYPE_MESSAGE_DIALOG, AppCenterMessageDialog))
#define APP_CENTER_MESSAGE_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_TYPE_MESSAGE_DIALOG, AppCenterMessageDialogClass))
#define APP_CENTER_IS_MESSAGE_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_TYPE_MESSAGE_DIALOG))
#define APP_CENTER_IS_MESSAGE_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_TYPE_MESSAGE_DIALOG))
#define APP_CENTER_MESSAGE_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_TYPE_MESSAGE_DIALOG, AppCenterMessageDialogClass))

typedef struct _AppCenterMessageDialog AppCenterMessageDialog;
typedef struct _AppCenterMessageDialogClass AppCenterMessageDialogClass;

struct _AppCenterApp {
	GraniteApplication parent_instance;
	AppCenterAppPrivate * priv;
};

struct _AppCenterAppClass {
	GraniteApplicationClass parent_class;
};

struct _AppCenterAppPrivate {
	AppCenterMainWindow* main_window;
	guint registration_id;
	guint cache_update_timeout_id;
};

struct _Block15Data {
	int _ref_count_;
	AppCenterApp* self;
	AppCenterCoreClient* client;
};

struct _Block16Data {
	int _ref_count_;
	AppCenterApp* self;
	AppCenterCoreClient* client;
};

typedef enum  {
	APP_CENTER_CORE_PACKAGE_STATE_NOT_INSTALLED,
	APP_CENTER_CORE_PACKAGE_STATE_INSTALLED,
	APP_CENTER_CORE_PACKAGE_STATE_INSTALLING,
	APP_CENTER_CORE_PACKAGE_STATE_UPDATE_AVAILABLE,
	APP_CENTER_CORE_PACKAGE_STATE_UPDATING,
	APP_CENTER_CORE_PACKAGE_STATE_REMOVING
} AppCenterCorePackageState;


static gpointer app_center_app_parent_class = NULL;
extern gboolean app_center_app_show_updates;
gboolean app_center_app_show_updates = FALSE;
extern gboolean app_center_app_silent;
gboolean app_center_app_silent = FALSE;

GType app_center_app_get_type (void) G_GNUC_CONST;
GType app_center_main_window_get_type (void) G_GNUC_CONST;
#define APP_CENTER_APP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CENTER_TYPE_APP, AppCenterAppPrivate))
enum  {
	APP_CENTER_APP_DUMMY_PROPERTY
};
#define APP_CENTER_APP_SECONDS_AFTER_NETWORK_UP 60
static void app_center_app_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint);
GType app_center_core_client_get_type (void) G_GNUC_CONST;
AppCenterCoreClient* app_center_core_client_get_default (void);
GType app_center_core_package_get_type (void) G_GNUC_CONST;
AppCenterCorePackage* app_center_core_client_get_package_for_component_id (AppCenterCoreClient* self, const gchar* id);
void app_center_main_window_show_package (AppCenterMainWindow* self, AppCenterCorePackage* package);
void app_center_main_window_search (AppCenterMainWindow* self, const gchar* term);
static void app_center_app_real_activate (GApplication* base);
static Block15Data* block15_data_ref (Block15Data* _data15_);
static void block15_data_unref (void * _userdata_);
static void ___lambda101_ (AppCenterApp* self, gboolean available);
static void app_center_app_schedule_cache_update (AppCenterApp* self, gboolean cancel);
static void ____lambda101__g_network_monitor_network_changed (GNetworkMonitor* _sender, gboolean available, gpointer self);
void app_center_core_client_update_cache (AppCenterCoreClient* self, gboolean force, GAsyncReadyCallback _callback_, gpointer _user_data_);
void app_center_core_client_update_cache_finish (AppCenterCoreClient* self, GAsyncResult* _res_);
AppCenterMainWindow* app_center_main_window_new (GtkApplication* app);
AppCenterMainWindow* app_center_main_window_construct (GType object_type, GtkApplication* app);
static void ___lambda103_ (Block15Data* _data15_);
static void ____lambda103__app_center_main_window_homepage_loaded (AppCenterMainWindow* _sender, gpointer self);
static void ___lambda104_ (AppCenterApp* self);
static void ____lambda104__gtk_widget_destroy (GtkWidget* _sender, gpointer self);
void app_center_main_window_go_to_installed (AppCenterMainWindow* self);
static gboolean app_center_app_real_dbus_register (GApplication* base, GDBusConnection* connection, const gchar* object_path, GError** error);
void dbus_server_init (void);
GType dbus_server_get_type (void) G_GNUC_CONST;
guint dbus_server_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
DBusServer* dbus_server_get_default (void);
static void app_center_app_real_dbus_unregister (GApplication* base, GDBusConnection* connection, const gchar* object_path);
static Block16Data* block16_data_ref (Block16Data* _data16_);
static void block16_data_unref (void * _userdata_);
void app_center_core_client_cancel_updates (AppCenterCoreClient* self, gboolean cancel_timeout);
static gboolean ___lambda102_ (Block16Data* _data16_);
static gboolean ____lambda102__gsource_func (gpointer self);
GType app_center_core_package_state_get_type (void) G_GNUC_CONST;
static void app_center_app_on_operation_finished (AppCenterApp* self, AppCenterCorePackage* package, AppCenterCorePackageState operation, GError* _error_);
gchar* app_center_core_package_get_name (AppCenterCorePackage* self);
GType app_center_message_dialog_get_type (void) G_GNUC_CONST;
AppCenterMessageDialog* app_center_message_dialog_new (const gchar* primary_text, const gchar* secondary_text, const gchar* image_icon_name);
AppCenterMessageDialog* app_center_message_dialog_construct (GType object_type, const gchar* primary_text, const gchar* secondary_text, const gchar* image_icon_name);
AppCenterApp* app_center_app_new (void);
AppCenterApp* app_center_app_construct (GType object_type);
static GObject * app_center_app_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
#define BUILD_GETTEXT_PACKAGE "appcenter"
#define BUILD_DESKTOP_ICON "system-software-install"
#define BUILD_DATADIR "/usr/share"
#define BUILD_PKGDATADIR "/usr/share/appcenter"
#define BUILD_RELEASE_NAME "Browse and manage apps"
#define BUILD_VERSION "0.2.3"
#define BUILD_VERSION_INFO "Alpha"
static void _app_center_app___lambda106_ (AppCenterApp* self);
static void __app_center_app___lambda106__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void _app_center_app___lambda107_ (AppCenterApp* self);
static void __app_center_app___lambda107__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void _app_center_app_on_operation_finished_app_center_core_client_operation_finished (AppCenterCoreClient* _sender, AppCenterCorePackage* package, AppCenterCorePackageState operation, GError* _error_, gpointer self);
static void app_center_app_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const GOptionEntry APP_CENTER_APP_appcenter_options[3] = {{"show-updates", 'u', 0, G_OPTION_ARG_NONE, &app_center_app_show_updates, "Display the Installed Panel", NULL}, {"silent", 's', 0, G_OPTION_ARG_NONE, &app_center_app_silent, "Run the Application in background", NULL}, {NULL}};

static gpointer _g_object_ref0 (gpointer self) {
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return self ? g_object_ref (self) : NULL;
#line 218 "Application.c"
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
#line 1380 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1380 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1380 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 231 "Application.c"
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp0_ = old;
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_free0 (_tmp2_);
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		regex = _tmp4_;
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 262 "Application.c"
				goto __catch19_g_regex_error;
			}
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1382 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			return NULL;
#line 271 "Application.c"
		}
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp6_ = regex;
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp7_ = replacement;
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) -1, 0, _tmp7_, 0, &_inner_error_);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp5_ = _tmp8_;
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 287 "Application.c"
				goto __catch19_g_regex_error;
			}
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			return NULL;
#line 298 "Application.c"
		}
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp9_ = _tmp5_;
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp5_ = NULL;
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = _tmp9_;
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_free0 (_tmp5_);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1383 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 312 "Application.c"
	}
	goto __finally19;
	__catch19_g_regex_error:
	{
		GError* e = NULL;
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		e = _inner_error_;
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_inner_error_ = NULL;
#line 1385 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_assert_not_reached ();
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_error_free0 (e);
#line 326 "Application.c"
	}
	__finally19:
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_clear_error (&_inner_error_);
#line 1381 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return NULL;
#line 337 "Application.c"
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 1295 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1295 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1295 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1295 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1296 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1296 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 361 "Application.c"
		glong _tmp4_ = 0L;
#line 1297 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1297 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1297 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 369 "Application.c"
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 1299 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1299 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1299 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1299 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 381 "Application.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
#line 1306 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1308 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1308 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 405 "Application.c"
		glong _tmp2_ = 0L;
#line 1308 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1308 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 411 "Application.c"
	} else {
#line 1308 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 415 "Application.c"
	}
#line 1308 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp0_) {
#line 419 "Application.c"
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
#line 1310 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp3_ = offset;
#line 1310 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = len;
#line 1310 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
#line 1310 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		string_length = _tmp5_;
#line 431 "Application.c"
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
#line 1312 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp6_ = strlen (self);
#line 1312 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp7_ = _tmp6_;
#line 1312 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp7_;
#line 441 "Application.c"
	}
#line 1315 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp8_ = offset;
#line 1315 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp8_ < ((glong) 0)) {
#line 447 "Application.c"
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
#line 1316 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp9_ = string_length;
#line 1316 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp10_ = offset;
#line 1316 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		offset = _tmp9_ + _tmp10_;
#line 1317 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1317 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
#line 461 "Application.c"
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
#line 1319 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1319 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp13_ = string_length;
#line 1319 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
#line 471 "Application.c"
	}
#line 1321 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp14_ = len;
#line 1321 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp14_ < ((glong) 0)) {
#line 477 "Application.c"
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
#line 1322 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp15_ = string_length;
#line 1322 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp16_ = offset;
#line 1322 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		len = _tmp15_ - _tmp16_;
#line 486 "Application.c"
	}
#line 1324 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp17_ = offset;
#line 1324 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp18_ = len;
#line 1324 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp19_ = string_length;
#line 1324 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
#line 1325 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp20_ = offset;
#line 1325 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp21_ = len;
#line 1325 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
#line 1325 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = _tmp22_;
#line 1325 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 506 "Application.c"
}


static gint string_last_index_of_char (const gchar* self, gunichar c, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	gunichar _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 1017 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 1018 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 1018 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = c;
#line 1018 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp2_ = g_utf8_strrchr (((gchar*) self) + _tmp0_, (gssize) -1, _tmp1_);
#line 1018 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 1020 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 1020 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 531 "Application.c"
		gchar* _tmp4_ = NULL;
#line 1021 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 1021 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 1021 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 539 "Application.c"
	} else {
#line 1023 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = -1;
#line 1023 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 545 "Application.c"
	}
}


static void app_center_app_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint) {
	AppCenterApp * self;
	GFile* file = NULL;
	GFile** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	gchar* link = NULL;
	GFile* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	AppCenterCoreClient* client = NULL;
	AppCenterCoreClient* _tmp17_ = NULL;
	AppCenterCoreClient* _tmp18_ = NULL;
	AppCenterCorePackage* package = NULL;
	AppCenterCoreClient* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	AppCenterCorePackage* _tmp21_ = NULL;
	AppCenterCorePackage* _tmp22_ = NULL;
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = (AppCenterApp*) base;
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_if_fail (hint != NULL);
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_application_activate ((GApplication*) self);
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = files;
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0__length1 = files_length1;
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1_ = _tmp0_[0];
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	file = _tmp2_;
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp3_ = file;
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp3_ == NULL) {
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (file);
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		return;
#line 600 "Application.c"
	}
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp4_ = file;
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp5_ = g_file_has_uri_scheme (_tmp4_, "appstream");
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (!_tmp5_) {
#line 101 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (file);
#line 101 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		return;
#line 612 "Application.c"
	}
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp6_ = file;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp7_ = g_file_get_uri (_tmp6_);
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp8_ = _tmp7_;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp9_ = string_replace (_tmp8_, "appstream://", "");
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp10_ = _tmp9_;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (_tmp8_);
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	link = _tmp10_;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp11_ = link;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp12_ = g_str_has_suffix (_tmp11_, "/");
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp12_) {
#line 634 "Application.c"
		const gchar* _tmp13_ = NULL;
		const gchar* _tmp14_ = NULL;
		gint _tmp15_ = 0;
		gchar* _tmp16_ = NULL;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp13_ = link;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp14_ = link;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp15_ = string_last_index_of_char (_tmp14_, (gunichar) '/', 0);
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp16_ = string_substring (_tmp13_, (glong) 0, (glong) _tmp15_);
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_free0 (link);
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		link = _tmp16_;
#line 651 "Application.c"
	}
#line 109 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp17_ = app_center_core_client_get_default ();
#line 109 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp18_ = _g_object_ref0 (_tmp17_);
#line 109 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	client = _tmp18_;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp19_ = client;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp20_ = link;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp21_ = app_center_core_client_get_package_for_component_id (_tmp19_, _tmp20_);
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	package = _tmp21_;
#line 111 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp22_ = package;
#line 111 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp22_ != NULL) {
#line 671 "Application.c"
		AppCenterMainWindow* _tmp23_ = NULL;
		AppCenterCorePackage* _tmp24_ = NULL;
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp23_ = self->priv->main_window;
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp24_ = package;
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		app_center_main_window_show_package (_tmp23_, _tmp24_);
#line 680 "Application.c"
	} else {
		const gchar* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_ = NULL;
		gchar* search_term = NULL;
		const gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		const gchar* _tmp31_ = NULL;
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp25_ = _ ("Specified link '%s' could not be found, searching instead");
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp26_ = link;
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp27_ = g_strdup_printf (_tmp25_, _tmp26_);
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp28_ = _tmp27_;
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_info ("Application.vala:114: %s", _tmp28_);
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_free0 (_tmp28_);
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp29_ = link;
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp30_ = g_uri_unescape_string (_tmp29_, NULL);
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		search_term = _tmp30_;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp31_ = search_term;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		if (_tmp31_ != NULL) {
#line 712 "Application.c"
			AppCenterMainWindow* _tmp32_ = NULL;
			const gchar* _tmp33_ = NULL;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp32_ = self->priv->main_window;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp33_ = search_term;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			app_center_main_window_search (_tmp32_, _tmp33_);
#line 721 "Application.c"
		}
#line 111 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_free0 (search_term);
#line 725 "Application.c"
	}
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (package);
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (client);
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (link);
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (file);
#line 735 "Application.c"
}


static Block15Data* block15_data_ref (Block15Data* _data15_) {
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_atomic_int_inc (&_data15_->_ref_count_);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return _data15_;
#line 744 "Application.c"
}


static void block15_data_unref (void * _userdata_) {
	Block15Data* _data15_;
	_data15_ = (Block15Data*) _userdata_;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (g_atomic_int_dec_and_test (&_data15_->_ref_count_)) {
#line 753 "Application.c"
		AppCenterApp* self;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		self = _data15_->self;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (_data15_->client);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (self);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_slice_free (Block15Data, _data15_);
#line 763 "Application.c"
	}
}


static void ___lambda101_ (AppCenterApp* self, gboolean available) {
	gboolean _tmp0_ = FALSE;
#line 126 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = available;
#line 126 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_app_schedule_cache_update (self, !_tmp0_);
#line 774 "Application.c"
}


static void ____lambda101__g_network_monitor_network_changed (GNetworkMonitor* _sender, gboolean available, gpointer self) {
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	___lambda101_ ((AppCenterApp*) self, available);
#line 781 "Application.c"
}


static void ___lambda103_ (Block15Data* _data15_) {
	AppCenterApp* self;
	AppCenterCoreClient* _tmp0_ = NULL;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = _data15_->self;
#line 139 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = _data15_->client;
#line 139 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_core_client_update_cache (_tmp0_, TRUE, NULL, NULL);
#line 794 "Application.c"
}


static void ____lambda103__app_center_main_window_homepage_loaded (AppCenterMainWindow* _sender, gpointer self) {
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	___lambda103_ (self);
#line 801 "Application.c"
}


static void ___lambda104_ (AppCenterApp* self) {
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (self->priv->main_window);
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self->priv->main_window = NULL;
#line 810 "Application.c"
}


static void ____lambda104__gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	___lambda104_ ((AppCenterApp*) self);
#line 817 "Application.c"
}


static void app_center_app_real_activate (GApplication* base) {
	AppCenterApp * self;
	Block15Data* _data15_;
	AppCenterCoreClient* _tmp0_ = NULL;
	AppCenterCoreClient* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	AppCenterMainWindow* _tmp5_ = NULL;
	AppCenterMainWindow* _tmp16_ = NULL;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = (AppCenterApp*) base;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data15_ = g_slice_new0 (Block15Data);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data15_->_ref_count_ = 1;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data15_->self = g_object_ref (self);
#line 123 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = app_center_core_client_get_default ();
#line 123 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 123 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data15_->client = _tmp1_;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp2_ = app_center_app_silent;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp2_) {
#line 847 "Application.c"
		GNetworkMonitor* _tmp3_ = NULL;
		AppCenterCoreClient* _tmp4_ = NULL;
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp3_ = g_network_monitor_get_default ();
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_signal_connect_object (_tmp3_, "network-changed", (GCallback) ____lambda101__g_network_monitor_network_changed, self, 0);
#line 129 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp4_ = _data15_->client;
#line 129 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		app_center_core_client_update_cache (_tmp4_, TRUE, NULL, NULL);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		app_center_app_silent = FALSE;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_application_hold ((GApplication*) self);
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		block15_data_unref (_data15_);
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_data15_ = NULL;
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		return;
#line 868 "Application.c"
	}
#line 135 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp5_ = self->priv->main_window;
#line 135 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp5_ == NULL) {
#line 874 "Application.c"
		AppCenterMainWindow* _tmp6_ = NULL;
		AppCenterMainWindow* _tmp7_ = NULL;
		AppCenterMainWindow* _tmp8_ = NULL;
		AppCenterMainWindow* _tmp9_ = NULL;
		AppCenterMainWindow* _tmp10_ = NULL;
		gboolean _tmp11_ = FALSE;
#line 136 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp6_ = app_center_main_window_new ((GtkApplication*) self);
#line 136 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_object_ref_sink (_tmp6_);
#line 136 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (self->priv->main_window);
#line 136 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		self->priv->main_window = _tmp6_;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp7_ = self->priv->main_window;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_signal_connect_data (_tmp7_, "homepage-loaded", (GCallback) ____lambda103__app_center_main_window_homepage_loaded, block15_data_ref (_data15_), (GClosureNotify) block15_data_unref, 0);
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp8_ = self->priv->main_window;
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_signal_connect_object ((GtkWidget*) _tmp8_, "destroy", (GCallback) ____lambda104__gtk_widget_destroy, self, 0);
#line 145 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp9_ = self->priv->main_window;
#line 145 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) _tmp9_);
#line 146 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp10_ = self->priv->main_window;
#line 146 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		gtk_widget_show_all ((GtkWidget*) _tmp10_);
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp11_ = app_center_app_show_updates;
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		if (_tmp11_) {
#line 909 "Application.c"
			AppCenterMainWindow* _tmp12_ = NULL;
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp12_ = self->priv->main_window;
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			app_center_main_window_go_to_installed (_tmp12_);
#line 915 "Application.c"
		}
	} else {
		gboolean _tmp13_ = FALSE;
#line 151 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp13_ = app_center_app_show_updates;
#line 151 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		if (_tmp13_) {
#line 923 "Application.c"
			AppCenterMainWindow* _tmp14_ = NULL;
			AppCenterMainWindow* _tmp15_ = NULL;
#line 152 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp14_ = self->priv->main_window;
#line 152 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			app_center_main_window_go_to_installed (_tmp14_);
#line 153 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp15_ = self->priv->main_window;
#line 153 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			gtk_window_present ((GtkWindow*) _tmp15_);
#line 934 "Application.c"
		}
	}
#line 157 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp16_ = self->priv->main_window;
#line 157 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	gtk_window_present ((GtkWindow*) _tmp16_);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	block15_data_unref (_data15_);
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data15_ = NULL;
#line 945 "Application.c"
}


static gboolean app_center_app_real_dbus_register (GApplication* base, GDBusConnection* connection, const gchar* object_path, GError** error) {
	AppCenterApp * self;
	gboolean result = FALSE;
	GDBusConnection* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp3_ = FALSE;
	GError * _inner_error_ = NULL;
#line 160 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = (AppCenterApp*) base;
#line 160 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_val_if_fail (connection != NULL, FALSE);
#line 160 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_val_if_fail (object_path != NULL, FALSE);
#line 161 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = connection;
#line 161 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1_ = object_path;
#line 161 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	G_APPLICATION_CLASS (app_center_app_parent_class)->dbus_register ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, GRANITE_TYPE_APPLICATION, GraniteApplication), _tmp0_, _tmp1_, &_inner_error_);
#line 161 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 970 "Application.c"
		gboolean _tmp2_ = FALSE;
#line 161 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_propagate_error (error, _inner_error_);
#line 161 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		return _tmp2_;
#line 976 "Application.c"
	}
#line 163 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp3_ = app_center_app_silent;
#line 163 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp3_) {
#line 164 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		dbus_server_init ();
#line 984 "Application.c"
		{
			guint _tmp4_ = 0U;
			GDBusConnection* _tmp5_ = NULL;
			DBusServer* _tmp6_ = NULL;
			guint _tmp7_ = 0U;
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp5_ = connection;
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp6_ = dbus_server_get_default ();
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp7_ = dbus_server_register_object (_tmp6_, _tmp5_, "/io/elementary/appcenter", &_inner_error_);
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp4_ = _tmp7_;
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1000 "Application.c"
				goto __catch20_g_error;
			}
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			self->priv->registration_id = _tmp4_;
#line 1005 "Application.c"
		}
		goto __finally20;
		__catch20_g_error:
		{
			GError* e = NULL;
			GError* _tmp8_ = NULL;
			const gchar* _tmp9_ = NULL;
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			e = _inner_error_;
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_inner_error_ = NULL;
#line 168 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp8_ = e;
#line 168 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp9_ = _tmp8_->message;
#line 168 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			g_warning ("Application.vala:168: %s", _tmp9_);
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_g_error_free0 (e);
#line 1025 "Application.c"
		}
		__finally20:
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1030 "Application.c"
			gboolean _tmp10_ = FALSE;
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			g_propagate_error (error, _inner_error_);
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			return _tmp10_;
#line 1036 "Application.c"
		}
	}
#line 172 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	result = TRUE;
#line 172 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return result;
#line 1043 "Application.c"
}


static void app_center_app_real_dbus_unregister (GApplication* base, GDBusConnection* connection, const gchar* object_path) {
	AppCenterApp * self;
	guint _tmp0_ = 0U;
	GDBusConnection* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = (AppCenterApp*) base;
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_if_fail (connection != NULL);
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_if_fail (object_path != NULL);
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = self->priv->registration_id;
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp0_ != ((guint) 0)) {
#line 1062 "Application.c"
		GDBusConnection* _tmp1_ = NULL;
		guint _tmp2_ = 0U;
#line 177 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp1_ = connection;
#line 177 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp2_ = self->priv->registration_id;
#line 177 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_dbus_connection_unregister_object (_tmp1_, _tmp2_);
#line 1071 "Application.c"
	}
#line 180 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp3_ = connection;
#line 180 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp4_ = object_path;
#line 180 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	G_APPLICATION_CLASS (app_center_app_parent_class)->dbus_unregister ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, GRANITE_TYPE_APPLICATION, GraniteApplication), _tmp3_, _tmp4_);
#line 1079 "Application.c"
}


static Block16Data* block16_data_ref (Block16Data* _data16_) {
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_atomic_int_inc (&_data16_->_ref_count_);
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return _data16_;
#line 1088 "Application.c"
}


static void block16_data_unref (void * _userdata_) {
	Block16Data* _data16_;
	_data16_ = (Block16Data*) _userdata_;
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (g_atomic_int_dec_and_test (&_data16_->_ref_count_)) {
#line 1097 "Application.c"
		AppCenterApp* self;
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		self = _data16_->self;
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (_data16_->client);
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (self);
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_slice_free (Block16Data, _data16_);
#line 1107 "Application.c"
	}
}


static gboolean ___lambda102_ (Block16Data* _data16_) {
	AppCenterApp* self;
	gboolean result = FALSE;
	AppCenterCoreClient* _tmp0_ = NULL;
#line 196 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = _data16_->self;
#line 197 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = _data16_->client;
#line 197 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_core_client_update_cache (_tmp0_, FALSE, NULL, NULL);
#line 198 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self->priv->cache_update_timeout_id = (guint) 0;
#line 199 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	result = FALSE;
#line 199 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return result;
#line 1128 "Application.c"
}


static gboolean ____lambda102__gsource_func (gpointer self) {
	gboolean result;
	result = ___lambda102_ (self);
#line 196 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return result;
#line 1137 "Application.c"
}


static void app_center_app_schedule_cache_update (AppCenterApp* self, gboolean cancel) {
	Block16Data* _data16_;
	AppCenterCoreClient* _tmp0_ = NULL;
	AppCenterCoreClient* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	gboolean _tmp4_ = FALSE;
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_if_fail (self != NULL);
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data16_ = g_slice_new0 (Block16Data);
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data16_->_ref_count_ = 1;
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data16_->self = g_object_ref (self);
#line 185 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = app_center_core_client_get_default ();
#line 185 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 185 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data16_->client = _tmp1_;
#line 187 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp2_ = self->priv->cache_update_timeout_id;
#line 187 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp2_ > ((guint) 0)) {
#line 1165 "Application.c"
		guint _tmp3_ = 0U;
#line 188 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp3_ = self->priv->cache_update_timeout_id;
#line 188 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		g_source_remove (_tmp3_);
#line 189 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		self->priv->cache_update_timeout_id = (guint) 0;
#line 1173 "Application.c"
	}
#line 192 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp4_ = cancel;
#line 192 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp4_) {
#line 1179 "Application.c"
		AppCenterCoreClient* _tmp5_ = NULL;
#line 193 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp5_ = _data16_->client;
#line 193 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		app_center_core_client_cancel_updates (_tmp5_, TRUE);
#line 194 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		block16_data_unref (_data16_);
#line 194 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_data16_ = NULL;
#line 194 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		return;
#line 1191 "Application.c"
	} else {
		guint _tmp6_ = 0U;
#line 196 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp6_ = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) APP_CENTER_APP_SECONDS_AFTER_NETWORK_UP, ____lambda102__gsource_func, block16_data_ref (_data16_), block16_data_unref);
#line 196 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		self->priv->cache_update_timeout_id = _tmp6_;
#line 1198 "Application.c"
	}
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	block16_data_unref (_data16_);
#line 184 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_data16_ = NULL;
#line 1204 "Application.c"
}


static void app_center_app_on_operation_finished (AppCenterApp* self, AppCenterCorePackage* package, AppCenterCorePackageState operation, GError* _error_) {
	AppCenterCorePackageState _tmp0_ = 0;
#line 204 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_if_fail (self != NULL);
#line 204 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_return_if_fail (package != NULL);
#line 205 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = operation;
#line 205 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	switch (_tmp0_) {
#line 205 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		case APP_CENTER_CORE_PACKAGE_STATE_INSTALLING:
#line 1220 "Application.c"
		{
			GError* _tmp1_ = NULL;
#line 207 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp1_ = _error_;
#line 207 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			if (_tmp1_ == NULL) {
#line 1227 "Application.c"
				AppCenterMainWindow* _tmp2_ = NULL;
				GNotification* notification = NULL;
				const gchar* _tmp10_ = NULL;
				GNotification* _tmp11_ = NULL;
				GNotification* _tmp12_ = NULL;
				const gchar* _tmp13_ = NULL;
				AppCenterCorePackage* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				gchar* _tmp16_ = NULL;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				GNotification* _tmp19_ = NULL;
				GThemedIcon* _tmp20_ = NULL;
				GThemedIcon* _tmp21_ = NULL;
				GNotification* _tmp22_ = NULL;
				GNotification* _tmp23_ = NULL;
#line 209 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp2_ = self->priv->main_window;
#line 209 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				if (_tmp2_ != NULL) {
#line 1248 "Application.c"
					GdkWindow* win = NULL;
					AppCenterMainWindow* _tmp3_ = NULL;
					GdkWindow* _tmp4_ = NULL;
					GdkWindow* _tmp5_ = NULL;
					gboolean _tmp6_ = FALSE;
					GdkWindow* _tmp7_ = NULL;
#line 210 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp3_ = self->priv->main_window;
#line 210 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp4_ = gtk_widget_get_window ((GtkWidget*) _tmp3_);
#line 210 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp5_ = _g_object_ref0 (_tmp4_);
#line 210 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					win = _tmp5_;
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp7_ = win;
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					if (_tmp7_ != NULL) {
#line 1267 "Application.c"
						GdkWindow* _tmp8_ = NULL;
						GdkWindowState _tmp9_ = 0;
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
						_tmp8_ = win;
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
						_tmp9_ = gdk_window_get_state (_tmp8_);
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
						_tmp6_ = (_tmp9_ & GDK_WINDOW_STATE_FOCUSED) != 0;
#line 1276 "Application.c"
					} else {
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
						_tmp6_ = FALSE;
#line 1280 "Application.c"
					}
#line 211 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					if (_tmp6_) {
#line 212 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
						_g_object_unref0 (win);
#line 212 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
						break;
#line 1288 "Application.c"
					}
#line 209 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_g_object_unref0 (win);
#line 1292 "Application.c"
				}
#line 216 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp10_ = _ ("Application installed");
#line 216 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp11_ = g_notification_new (_tmp10_);
#line 216 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				notification = _tmp11_;
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp12_ = notification;
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp13_ = _ ("%s has been successfully installed");
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp14_ = package;
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp15_ = app_center_core_package_get_name (_tmp14_);
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp16_ = _tmp15_;
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp17_ = g_strdup_printf (_tmp13_, _tmp16_);
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp18_ = _tmp17_;
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				g_notification_set_body (_tmp12_, _tmp18_);
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_free0 (_tmp18_);
#line 217 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_free0 (_tmp16_);
#line 218 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp19_ = notification;
#line 218 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp20_ = (GThemedIcon*) g_themed_icon_new ("system-software-install");
#line 218 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp21_ = _tmp20_;
#line 218 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				g_notification_set_icon (_tmp19_, (GIcon*) _tmp21_);
#line 218 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_object_unref0 (_tmp21_);
#line 219 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp22_ = notification;
#line 219 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				g_notification_set_default_action (_tmp22_, "app.open-application");
#line 221 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp23_ = notification;
#line 221 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				g_application_send_notification ((GApplication*) self, "installed", _tmp23_);
#line 207 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_object_unref0 (notification);
#line 1340 "Application.c"
			} else {
				gboolean _tmp24_ = FALSE;
				GError* _tmp25_ = NULL;
				GQuark _tmp26_ = 0U;
				gboolean _tmp27_ = FALSE;
				gchar* body = NULL;
				GError* _tmp31_ = NULL;
				const gchar* _tmp32_ = NULL;
				gchar* _tmp33_ = NULL;
				const gchar* _tmp34_ = NULL;
				gboolean _tmp35_ = FALSE;
				GtkButton* close_button = NULL;
				const gchar* _tmp38_ = NULL;
				GtkButton* _tmp39_ = NULL;
				AppCenterMessageDialog* dialog = NULL;
				const gchar* _tmp40_ = NULL;
				AppCenterCorePackage* _tmp41_ = NULL;
				gchar* _tmp42_ = NULL;
				gchar* _tmp43_ = NULL;
				gchar* _tmp44_ = NULL;
				gchar* _tmp45_ = NULL;
				const gchar* _tmp46_ = NULL;
				AppCenterMessageDialog* _tmp47_ = NULL;
				AppCenterMessageDialog* _tmp48_ = NULL;
				AppCenterMessageDialog* _tmp49_ = NULL;
				GtkButton* _tmp50_ = NULL;
				AppCenterMessageDialog* _tmp51_ = NULL;
				AppCenterMessageDialog* _tmp52_ = NULL;
				AppCenterMessageDialog* _tmp53_ = NULL;
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp25_ = _error_;
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp26_ = g_io_error_quark ();
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp27_ = g_error_matches (_tmp25_, _tmp26_, 19);
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				if (_tmp27_) {
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp24_ = TRUE;
#line 1380 "Application.c"
				} else {
					GError* _tmp28_ = NULL;
					GQuark _tmp29_ = 0U;
					gboolean _tmp30_ = FALSE;
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp28_ = _error_;
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp29_ = pk_client_error_quark ();
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp30_ = g_error_matches (_tmp28_, _tmp29_, 303);
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp24_ = _tmp30_;
#line 1393 "Application.c"
				}
#line 224 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				if (_tmp24_) {
#line 225 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					break;
#line 1399 "Application.c"
				}
#line 228 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp31_ = _error_;
#line 228 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp32_ = _tmp31_->message;
#line 228 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp33_ = g_strdup (_tmp32_);
#line 228 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				body = _tmp33_;
#line 229 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp34_ = body;
#line 229 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp35_ = g_str_has_suffix (_tmp34_, ".");
#line 229 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				if (!_tmp35_) {
#line 1415 "Application.c"
					const gchar* _tmp36_ = NULL;
					gchar* _tmp37_ = NULL;
#line 230 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp36_ = body;
#line 230 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_tmp37_ = g_strconcat (_tmp36_, ".", NULL);
#line 230 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					_g_free0 (body);
#line 230 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
					body = _tmp37_;
#line 1426 "Application.c"
				}
#line 233 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp38_ = _ ("Close");
#line 233 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp39_ = (GtkButton*) gtk_button_new_with_label (_tmp38_);
#line 233 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				g_object_ref_sink (_tmp39_);
#line 233 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				close_button = _tmp39_;
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp40_ = _ ("There Was An Error Installing %s");
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp41_ = package;
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp42_ = app_center_core_package_get_name (_tmp41_);
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp43_ = _tmp42_;
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp44_ = g_strdup_printf (_tmp40_, _tmp43_);
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp45_ = _tmp44_;
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp46_ = body;
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp47_ = app_center_message_dialog_new (_tmp45_, _tmp46_, "dialog-error");
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				g_object_ref_sink (_tmp47_);
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp48_ = _tmp47_;
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_free0 (_tmp45_);
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_free0 (_tmp43_);
#line 235 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				dialog = _tmp48_;
#line 236 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp49_ = dialog;
#line 236 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp50_ = close_button;
#line 236 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				gtk_dialog_add_action_widget ((GtkDialog*) _tmp49_, (GtkWidget*) _tmp50_, 0);
#line 237 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp51_ = dialog;
#line 237 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				gtk_widget_show_all ((GtkWidget*) _tmp51_);
#line 238 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp52_ = dialog;
#line 238 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				gtk_dialog_run ((GtkDialog*) _tmp52_);
#line 239 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_tmp53_ = dialog;
#line 239 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				gtk_widget_destroy ((GtkWidget*) _tmp53_);
#line 207 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_object_unref0 (dialog);
#line 207 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_object_unref0 (close_button);
#line 207 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
				_g_free0 (body);
#line 1486 "Application.c"
			}
#line 242 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			break;
#line 1490 "Application.c"
		}
		default:
		{
#line 244 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			break;
#line 1496 "Application.c"
		}
	}
}


AppCenterApp* app_center_app_construct (GType object_type) {
	AppCenterApp * self = NULL;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = (AppCenterApp*) granite_application_construct (object_type);
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return self;
#line 1508 "Application.c"
}


AppCenterApp* app_center_app_new (void) {
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return app_center_app_construct (APP_CENTER_TYPE_APP);
#line 1515 "Application.c"
}


static void _app_center_app___lambda106_ (AppCenterApp* self) {
	AppCenterMainWindow* _tmp0_ = NULL;
#line 63 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = self->priv->main_window;
#line 63 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp0_ != NULL) {
#line 1525 "Application.c"
		AppCenterMainWindow* _tmp1_ = NULL;
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp1_ = self->priv->main_window;
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		gtk_widget_destroy ((GtkWidget*) _tmp1_);
#line 1531 "Application.c"
	}
}


static void __app_center_app___lambda106__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_app_center_app___lambda106_ ((AppCenterApp*) self);
#line 1539 "Application.c"
}


static void _app_center_app___lambda107_ (AppCenterApp* self) {
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_app_silent = FALSE;
#line 71 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_app_show_updates = TRUE;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_application_activate ((GApplication*) self);
#line 1550 "Application.c"
}


static void __app_center_app___lambda107__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_app_center_app___lambda107_ ((AppCenterApp*) self);
#line 1557 "Application.c"
}


static void _app_center_app_on_operation_finished_app_center_core_client_operation_finished (AppCenterCoreClient* _sender, AppCenterCorePackage* package, AppCenterCorePackageState operation, GError* _error_, gpointer self) {
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_app_on_operation_finished ((AppCenterApp*) self, package, operation, _error_);
#line 1564 "Application.c"
}


static GObject * app_center_app_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterApp * self;
	GApplicationFlags _tmp0_ = 0;
	GApplicationFlags _tmp1_ = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar** _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	GSimpleAction* quit_action = NULL;
	GSimpleAction* _tmp21_ = NULL;
	GSimpleAction* _tmp22_ = NULL;
	GSimpleAction* show_updates_action = NULL;
	GSimpleAction* _tmp23_ = NULL;
	GSimpleAction* _tmp24_ = NULL;
	AppCenterCoreClient* client = NULL;
	AppCenterCoreClient* _tmp25_ = NULL;
	AppCenterCoreClient* _tmp26_ = NULL;
	AppCenterCoreClient* _tmp27_ = NULL;
	GAppInfo* _tmp28_ = NULL;
	GAppInfo* _tmp29_ = NULL;
	gboolean _tmp30_ = FALSE;
	GSimpleAction* _tmp36_ = NULL;
	GSimpleAction* _tmp37_ = NULL;
	GError * _inner_error_ = NULL;
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	parent_class = G_OBJECT_CLASS (app_center_app_parent_class);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_TYPE_APP, AppCenterApp);
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_application_set_application_id ((GApplication*) self, "io.elementary.appcenter");
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = g_application_get_flags ((GApplication*) self);
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1_ = _tmp0_;
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_application_set_flags ((GApplication*) self, _tmp1_ | G_APPLICATION_HANDLES_OPEN);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	setlocale (LC_ALL, "");
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	textdomain (BUILD_GETTEXT_PACKAGE);
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp2_ = _ ("App Center");
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->program_name);
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->program_name = _tmp3_;
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp4_ = g_strdup ("2015-2017");
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->app_years);
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->app_years = _tmp4_;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp5_ = g_strdup (BUILD_DESKTOP_ICON);
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->app_icon);
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->app_icon = _tmp5_;
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp6_ = g_strdup (BUILD_DATADIR);
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->build_data_dir);
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->build_data_dir = _tmp6_;
#line 45 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp7_ = g_strdup (BUILD_PKGDATADIR);
#line 45 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->build_pkg_data_dir);
#line 45 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->build_pkg_data_dir = _tmp7_;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp8_ = g_strdup (BUILD_RELEASE_NAME);
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->build_release_name);
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->build_release_name = _tmp8_;
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp9_ = g_strdup (BUILD_VERSION);
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->build_version);
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->build_version = _tmp9_;
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp10_ = g_strdup (BUILD_VERSION_INFO);
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->build_version_info);
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->build_version_info = _tmp10_;
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp11_ = g_strdup ("io.elementary.appcenter.desktop");
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->app_launcher);
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->app_launcher = _tmp11_;
#line 51 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp12_ = g_strdup ("https://elementary.io");
#line 51 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->main_url);
#line 51 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->main_url = _tmp12_;
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp13_ = g_strdup ("https://github.com/elementary/appcenter/issues");
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->bug_url);
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->bug_url = _tmp13_;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp14_ = g_strdup ("https://elementary.io/support");
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->help_url);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->help_url = _tmp14_;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp15_ = g_strdup ("https://l10n.elementary.io/projects/appcenter");
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->translate_url);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->translate_url = _tmp15_;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp16_ = g_strdup ("Corentin Noël <corentin@elementary.io>");
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp17_ = g_new0 (gchar*, 1 + 1);
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp17_[0] = _tmp16_;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->about_authors = (_vala_array_free (((GraniteApplication*) self)->about_authors, ((GraniteApplication*) self)->about_authors_length1, (GDestroyNotify) g_free), NULL);
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->about_authors = _tmp17_;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->about_authors_length1 = 1;
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp18_ = g_strdup ("");
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->about_comments);
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->about_comments = _tmp18_;
#line 57 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp19_ = _ ("translator-credits");
#line 57 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp20_ = g_strdup (_tmp19_);
#line 57 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_free0 (((GraniteApplication*) self)->about_translators);
#line 57 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->about_translators = _tmp20_;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GraniteApplication*) self)->about_license_type = GTK_LICENSE_GPL_3_0;
#line 59 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_application_add_main_option_entries ((GApplication*) self, APP_CENTER_APP_appcenter_options);
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp21_ = g_simple_action_new ("quit", NULL);
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	quit_action = _tmp21_;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp22_ = quit_action;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_signal_connect_object (_tmp22_, "activate", (GCallback) __app_center_app___lambda106__g_simple_action_activate, self, 0);
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp23_ = g_simple_action_new ("show-updates", NULL);
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	show_updates_action = _tmp23_;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp24_ = show_updates_action;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_signal_connect_object (_tmp24_, "activate", (GCallback) __app_center_app___lambda107__g_simple_action_activate, self, 0);
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp25_ = app_center_core_client_get_default ();
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp26_ = _g_object_ref0 (_tmp25_);
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	client = _tmp26_;
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp27_ = client;
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_signal_connect_object (_tmp27_, "operation-finished", (GCallback) _app_center_app_on_operation_finished_app_center_core_client_operation_finished, self, 0);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp28_ = g_app_info_get_default_for_uri_scheme ("appstream");
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp29_ = _tmp28_;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp30_ = _tmp29_ == NULL;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (_tmp29_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	if (_tmp30_) {
#line 1773 "Application.c"
		GDesktopAppInfo* appinfo = NULL;
		const gchar* _tmp31_ = NULL;
		GDesktopAppInfo* _tmp32_ = NULL;
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp31_ = ((GraniteApplication*) self)->app_launcher;
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_tmp32_ = g_desktop_app_info_new (_tmp31_);
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		appinfo = _tmp32_;
#line 1783 "Application.c"
		{
			GDesktopAppInfo* _tmp33_ = NULL;
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp33_ = appinfo;
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			g_app_info_set_as_default_for_type ((GAppInfo*) _tmp33_, "x-scheme-handler/appstream", &_inner_error_);
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1792 "Application.c"
				goto __catch21_g_error;
			}
		}
		goto __finally21;
		__catch21_g_error:
		{
			GError* e = NULL;
			GError* _tmp34_ = NULL;
			const gchar* _tmp35_ = NULL;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			e = _inner_error_;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_inner_error_ = NULL;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp34_ = e;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_tmp35_ = _tmp34_->message;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			g_critical ("Application.vala:83: Unable to set default for the settings scheme: %s", _tmp35_);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_g_error_free0 (e);
#line 1814 "Application.c"
		}
		__finally21:
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_g_object_unref0 (appinfo);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_g_object_unref0 (client);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_g_object_unref0 (show_updates_action);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			_g_object_unref0 (quit_action);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
			g_clear_error (&_inner_error_);
#line 1831 "Application.c"
		}
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
		_g_object_unref0 (appinfo);
#line 1835 "Application.c"
	}
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp36_ = quit_action;
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp36_);
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp37_ = show_updates_action;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp37_);
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	gtk_application_add_accelerator ((GtkApplication*) self, "<Control>q", "app.quit", NULL);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (client);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (show_updates_action);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (quit_action);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return obj;
#line 1855 "Application.c"
}


static void app_center_app_class_init (AppCenterAppClass * klass) {
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	app_center_app_parent_class = g_type_class_peek_parent (klass);
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	g_type_class_add_private (klass, sizeof (AppCenterAppPrivate));
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GApplicationClass *) klass)->open = (void (*)(GApplication*, GFile**, int, const gchar*)) app_center_app_real_open;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GApplicationClass *) klass)->activate = (void (*)(GApplication*)) app_center_app_real_activate;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GApplicationClass *) klass)->dbus_register = (gboolean (*)(GApplication*, GDBusConnection*, const gchar*, GError**)) app_center_app_real_dbus_register;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	((GApplicationClass *) klass)->dbus_unregister = (void (*)(GApplication*, GDBusConnection*, const gchar*)) app_center_app_real_dbus_unregister;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_app_constructor;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	G_OBJECT_CLASS (klass)->finalize = app_center_app_finalize;
#line 1876 "Application.c"
}


static void app_center_app_instance_init (AppCenterApp * self) {
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self->priv = APP_CENTER_APP_GET_PRIVATE (self);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self->priv->registration_id = (guint) 0;
#line 183 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self->priv->cache_update_timeout_id = (guint) 0;
#line 1887 "Application.c"
}


static void app_center_app_finalize (GObject* obj) {
	AppCenterApp * self;
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_TYPE_APP, AppCenterApp);
#line 30 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (self->priv->main_window);
#line 17 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	G_OBJECT_CLASS (app_center_app_parent_class)->finalize (obj);
#line 1899 "Application.c"
}


GType app_center_app_get_type (void) {
	static volatile gsize app_center_app_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterApp), 0, (GInstanceInitFunc) app_center_app_instance_init, NULL };
		GType app_center_app_type_id;
		app_center_app_type_id = g_type_register_static (GRANITE_TYPE_APPLICATION, "AppCenterApp", &g_define_type_info, 0);
		g_once_init_leave (&app_center_app_type_id__volatile, app_center_app_type_id);
	}
	return app_center_app_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	AppCenterApp* application = NULL;
	AppCenterApp* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
#line 250 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp0_ = app_center_app_new ();
#line 250 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	application = _tmp0_;
#line 251 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1_ = args;
#line 251 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp1__length1 = args_length1;
#line 251 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_tmp2_ = granite_application_run ((GraniteApplication*) application, _tmp1_, _tmp1__length1);
#line 251 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	result = _tmp2_;
#line 251 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	_g_object_unref0 (application);
#line 251 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return result;
#line 1938 "Application.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,32,0)
	g_thread_init (NULL);
#endif
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 249 "/home/kedarbrooks/Documents/Projects/AppStore/src/Application.vala"
	return _vala_main (argv, argc);
#line 1951 "Application.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



