/* config.c generated by valac 0.34.8, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define BUILD_DATADIR "/usr/share"
#define BUILD_PKGDATADIR "/usr/share/appcenter"
#define BUILD_GETTEXT_PACKAGE "appcenter"
#define BUILD_RELEASE_NAME "Browse and manage apps"
#define BUILD_VERSION "0.2.3"
#define BUILD_VERSION_INFO "Alpha"
#define BUILD_DESKTOP_ICON "system-software-install"



