/* AbstractAppList.c generated by valac 0.34.8, the Vala compiler
 * generated from AbstractAppList.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2014-2016 elementary LLC. (https://elementary.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: Corentin Noël <corentin@elementary.io>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <glib/gi18n-lib.h>


#define APP_CENTER_TYPE_ABSTRACT_APP_LIST (app_center_abstract_app_list_get_type ())
#define APP_CENTER_ABSTRACT_APP_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_TYPE_ABSTRACT_APP_LIST, AppCenterAbstractAppList))
#define APP_CENTER_ABSTRACT_APP_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_TYPE_ABSTRACT_APP_LIST, AppCenterAbstractAppListClass))
#define APP_CENTER_IS_ABSTRACT_APP_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_TYPE_ABSTRACT_APP_LIST))
#define APP_CENTER_IS_ABSTRACT_APP_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_TYPE_ABSTRACT_APP_LIST))
#define APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_TYPE_ABSTRACT_APP_LIST, AppCenterAbstractAppListClass))

typedef struct _AppCenterAbstractAppList AppCenterAbstractAppList;
typedef struct _AppCenterAbstractAppListClass AppCenterAbstractAppListClass;
typedef struct _AppCenterAbstractAppListPrivate AppCenterAbstractAppListPrivate;

#define APP_CENTER_CORE_TYPE_PACKAGE (app_center_core_package_get_type ())
#define APP_CENTER_CORE_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackage))
#define APP_CENTER_CORE_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))
#define APP_CENTER_CORE_IS_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_IS_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_PACKAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))

typedef struct _AppCenterCorePackage AppCenterCorePackage;
typedef struct _AppCenterCorePackageClass AppCenterCorePackageClass;

#define APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW (app_center_widgets_app_list_row_get_type ())
#define APP_CENTER_WIDGETS_APP_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRow))
#define APP_CENTER_WIDGETS_IS_APP_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW))
#define APP_CENTER_WIDGETS_APP_LIST_ROW_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRowIface))

typedef struct _AppCenterWidgetsAppListRow AppCenterWidgetsAppListRow;
typedef struct _AppCenterWidgetsAppListRowIface AppCenterWidgetsAppListRowIface;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _AppCenterWidgetsAppListRowIface {
	GTypeInterface parent_iface;
	gboolean (*get_update_available) (AppCenterWidgetsAppListRow* self);
	gboolean (*get_is_os_updates) (AppCenterWidgetsAppListRow* self);
	gboolean (*get_is_driver) (AppCenterWidgetsAppListRow* self);
	gboolean (*get_is_updating) (AppCenterWidgetsAppListRow* self);
	gchar* (*get_name_label) (AppCenterWidgetsAppListRow* self);
	gboolean (*has_package) (AppCenterWidgetsAppListRow* self);
	AppCenterCorePackage* (*get_package) (AppCenterWidgetsAppListRow* self);
};

struct _AppCenterAbstractAppList {
	GtkBox parent_instance;
	AppCenterAbstractAppListPrivate * priv;
	GtkScrolledWindow* scrolled;
	GtkListBox* list_box;
	GtkSizeGroup* action_button_group;
	guint packages_changing;
};

struct _AppCenterAbstractAppListClass {
	GtkBoxClass parent_class;
	void (*add_packages) (AppCenterAbstractAppList* self, GeeCollection* packages);
	void (*add_package) (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
	void (*clear) (AppCenterAbstractAppList* self);
	AppCenterWidgetsAppListRow* (*make_row) (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
	void (*set_up_row) (AppCenterAbstractAppList* self, AppCenterWidgetsAppListRow* row);
	void (*after_add_remove_change_row) (AppCenterAbstractAppList* self);
	GeeCollection* (*get_packages) (AppCenterAbstractAppList* self);
	gint (*package_row_compare) (AppCenterWidgetsAppListRow* row1, AppCenterWidgetsAppListRow* row2, AppCenterAbstractAppList* self);
	void (*on_package_changing) (AppCenterAbstractAppList* self, AppCenterCorePackage* package, gboolean is_changing);
};


static gpointer app_center_abstract_app_list_parent_class = NULL;

GType app_center_abstract_app_list_get_type (void) G_GNUC_CONST;
GType app_center_core_package_get_type (void) G_GNUC_CONST;
GType app_center_widgets_app_list_row_get_type (void) G_GNUC_CONST;
enum  {
	APP_CENTER_ABSTRACT_APP_LIST_DUMMY_PROPERTY
};
void app_center_abstract_app_list_add_packages (AppCenterAbstractAppList* self, GeeCollection* packages);
static void app_center_abstract_app_list_real_add_packages (AppCenterAbstractAppList* self, GeeCollection* packages);
AppCenterWidgetsAppListRow* app_center_abstract_app_list_make_row (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
void app_center_abstract_app_list_set_up_row (AppCenterAbstractAppList* self, AppCenterWidgetsAppListRow* row);
void app_center_abstract_app_list_after_add_remove_change_row (AppCenterAbstractAppList* self);
void app_center_abstract_app_list_add_package (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
static void app_center_abstract_app_list_real_add_package (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
void app_center_abstract_app_list_remove_package (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
void app_center_abstract_app_list_on_package_changing (AppCenterAbstractAppList* self, AppCenterCorePackage* package, gboolean is_changing);
static void _app_center_abstract_app_list_on_package_changing_app_center_core_package_changing (AppCenterCorePackage* _sender, gboolean is_changing, gpointer self);
gboolean app_center_widgets_app_list_row_has_package (AppCenterWidgetsAppListRow* self);
AppCenterCorePackage* app_center_widgets_app_list_row_get_package (AppCenterWidgetsAppListRow* self);
void app_center_abstract_app_list_clear (AppCenterAbstractAppList* self);
static void app_center_abstract_app_list_real_clear (AppCenterAbstractAppList* self);
static AppCenterWidgetsAppListRow* app_center_abstract_app_list_real_make_row (AppCenterAbstractAppList* self, AppCenterCorePackage* package);
static void app_center_abstract_app_list_real_set_up_row (AppCenterAbstractAppList* self, AppCenterWidgetsAppListRow* row);
static void app_center_abstract_app_list_real_after_add_remove_change_row (AppCenterAbstractAppList* self);
GeeCollection* app_center_abstract_app_list_get_packages (AppCenterAbstractAppList* self);
static GeeCollection* app_center_abstract_app_list_real_get_packages (AppCenterAbstractAppList* self);
gint app_center_abstract_app_list_package_row_compare (AppCenterWidgetsAppListRow* row1, AppCenterWidgetsAppListRow* row2, AppCenterAbstractAppList* self);
static gint app_center_abstract_app_list_real_package_row_compare (AppCenterWidgetsAppListRow* row1, AppCenterWidgetsAppListRow* row2, AppCenterAbstractAppList* self);
gchar* app_center_widgets_app_list_row_get_name_label (AppCenterWidgetsAppListRow* self);
static void app_center_abstract_app_list_real_on_package_changing (AppCenterAbstractAppList* self, AppCenterCorePackage* package, gboolean is_changing);
AppCenterAbstractAppList* app_center_abstract_app_list_construct (GType object_type);
static GObject * app_center_abstract_app_list_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _app_center_abstract_app_list___lambda44_ (AppCenterAbstractAppList* self, GtkListBoxRow* r);
static void __app_center_abstract_app_list___lambda44__gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self);
static void app_center_abstract_app_list_finalize (GObject* obj);


static void app_center_abstract_app_list_real_add_packages (AppCenterAbstractAppList* self, GeeCollection* packages) {
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (packages != NULL);
#line 146 "AbstractAppList.c"
	{
		GeeIterator* _package_it = NULL;
		GeeCollection* _tmp0_ = NULL;
		GeeIterator* _tmp1_ = NULL;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_tmp0_ = packages;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_tmp1_ = gee_iterable_iterator ((GeeIterable*) _tmp0_);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_package_it = _tmp1_;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		while (TRUE) {
#line 159 "AbstractAppList.c"
			GeeIterator* _tmp2_ = NULL;
			gboolean _tmp3_ = FALSE;
			AppCenterCorePackage* package = NULL;
			GeeIterator* _tmp4_ = NULL;
			gpointer _tmp5_ = NULL;
			AppCenterWidgetsAppListRow* row = NULL;
			AppCenterCorePackage* _tmp6_ = NULL;
			AppCenterWidgetsAppListRow* _tmp7_ = NULL;
			AppCenterWidgetsAppListRow* _tmp8_ = NULL;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp2_ = _package_it;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp3_ = gee_iterator_next (_tmp2_);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			if (!_tmp3_) {
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				break;
#line 177 "AbstractAppList.c"
			}
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp4_ = _package_it;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp5_ = gee_iterator_get (_tmp4_);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			package = (AppCenterCorePackage*) _tmp5_;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp6_ = package;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp7_ = app_center_abstract_app_list_make_row (self, _tmp6_);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			row = _tmp7_;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_tmp8_ = row;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			app_center_abstract_app_list_set_up_row (self, _tmp8_);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_g_object_unref0 (row);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			_g_object_unref0 (package);
#line 199 "AbstractAppList.c"
		}
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_g_object_unref0 (_package_it);
#line 203 "AbstractAppList.c"
	}
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	app_center_abstract_app_list_after_add_remove_change_row (self);
#line 207 "AbstractAppList.c"
}


void app_center_abstract_app_list_add_packages (AppCenterAbstractAppList* self, GeeCollection* packages) {
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->add_packages (self, packages);
#line 216 "AbstractAppList.c"
}


static void app_center_abstract_app_list_real_add_package (AppCenterAbstractAppList* self, AppCenterCorePackage* package) {
	AppCenterWidgetsAppListRow* row = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	AppCenterWidgetsAppListRow* _tmp1_ = NULL;
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (package != NULL);
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = package;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = app_center_abstract_app_list_make_row (self, _tmp0_);
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	row = _tmp1_;
#line 63 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	app_center_abstract_app_list_set_up_row (self, row);
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	app_center_abstract_app_list_after_add_remove_change_row (self);
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (row);
#line 238 "AbstractAppList.c"
}


void app_center_abstract_app_list_add_package (AppCenterAbstractAppList* self, AppCenterCorePackage* package) {
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->add_package (self, package);
#line 247 "AbstractAppList.c"
}


static void _app_center_abstract_app_list_on_package_changing_app_center_core_package_changing (AppCenterCorePackage* _sender, gboolean is_changing, gpointer self) {
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	app_center_abstract_app_list_on_package_changing ((AppCenterAbstractAppList*) self, _sender, is_changing);
#line 254 "AbstractAppList.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return self ? g_object_ref (self) : NULL;
#line 261 "AbstractAppList.c"
}


void app_center_abstract_app_list_remove_package (AppCenterAbstractAppList* self, AppCenterCorePackage* package) {
	AppCenterCorePackage* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	GtkListBox* _tmp2_ = NULL;
	GList* _tmp3_ = NULL;
#line 67 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 67 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (package != NULL);
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = package;
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_signal_parse_name ("changing", APP_CENTER_CORE_TYPE_PACKAGE, &_tmp1_, NULL, FALSE);
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_signal_handlers_disconnect_matched (_tmp0_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _app_center_abstract_app_list_on_package_changing_app_center_core_package_changing, self);
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp2_ = self->list_box;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp3_ = gtk_container_get_children ((GtkContainer*) _tmp2_);
#line 284 "AbstractAppList.c"
	{
		GList* r_collection = NULL;
		GList* r_it = NULL;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		r_collection = _tmp3_;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		for (r_it = r_collection; r_it != NULL; r_it = r_it->next) {
#line 292 "AbstractAppList.c"
			GtkWidget* r = NULL;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			r = (GtkWidget*) r_it->data;
#line 296 "AbstractAppList.c"
			{
				AppCenterWidgetsAppListRow* row = NULL;
				GtkWidget* _tmp4_ = NULL;
				AppCenterWidgetsAppListRow* _tmp5_ = NULL;
				AppCenterWidgetsAppListRow* _tmp6_ = NULL;
				gboolean _tmp7_ = FALSE;
				AppCenterWidgetsAppListRow* _tmp8_ = NULL;
				AppCenterCorePackage* _tmp9_ = NULL;
				AppCenterCorePackage* _tmp10_ = NULL;
				AppCenterCorePackage* _tmp11_ = NULL;
				gboolean _tmp12_ = FALSE;
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp4_ = r;
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRow));
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				row = _tmp5_;
#line 71 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp6_ = row;
#line 71 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp7_ = app_center_widgets_app_list_row_has_package (_tmp6_);
#line 71 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				if (!_tmp7_) {
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_g_object_unref0 (row);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					continue;
#line 324 "AbstractAppList.c"
				}
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp8_ = row;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp9_ = app_center_widgets_app_list_row_get_package (_tmp8_);
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp10_ = _tmp9_;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp11_ = package;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp12_ = _tmp10_ == _tmp11_;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_g_object_unref0 (_tmp10_);
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				if (_tmp12_) {
#line 340 "AbstractAppList.c"
					AppCenterWidgetsAppListRow* _tmp13_ = NULL;
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp13_ = row;
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					gtk_widget_destroy ((GtkWidget*) _tmp13_);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_g_object_unref0 (row);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					break;
#line 350 "AbstractAppList.c"
				}
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_g_object_unref0 (row);
#line 354 "AbstractAppList.c"
			}
		}
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_g_list_free0 (r_collection);
#line 359 "AbstractAppList.c"
	}
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	app_center_abstract_app_list_after_add_remove_change_row (self);
#line 363 "AbstractAppList.c"
}


static void app_center_abstract_app_list_real_clear (AppCenterAbstractAppList* self) {
	GtkListBox* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = self->list_box;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
#line 374 "AbstractAppList.c"
	{
		GList* r_collection = NULL;
		GList* r_it = NULL;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		r_collection = _tmp1_;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		for (r_it = r_collection; r_it != NULL; r_it = r_it->next) {
#line 382 "AbstractAppList.c"
			GtkWidget* r = NULL;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			r = (GtkWidget*) r_it->data;
#line 386 "AbstractAppList.c"
			{
				AppCenterWidgetsAppListRow* row = NULL;
				GtkWidget* _tmp2_ = NULL;
				AppCenterWidgetsAppListRow* _tmp3_ = NULL;
				AppCenterWidgetsAppListRow* _tmp4_ = NULL;
				gboolean _tmp5_ = FALSE;
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp2_ = r;
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRow));
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				row = _tmp3_;
#line 85 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp4_ = row;
#line 85 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp5_ = app_center_widgets_app_list_row_has_package (_tmp4_);
#line 85 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				if (_tmp5_) {
#line 405 "AbstractAppList.c"
					AppCenterCorePackage* package = NULL;
					AppCenterWidgetsAppListRow* _tmp6_ = NULL;
					AppCenterCorePackage* _tmp7_ = NULL;
					AppCenterCorePackage* _tmp8_ = NULL;
					guint _tmp9_ = 0U;
					AppCenterWidgetsAppListRow* _tmp10_ = NULL;
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp6_ = row;
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp7_ = app_center_widgets_app_list_row_get_package (_tmp6_);
#line 86 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					package = _tmp7_;
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp8_ = package;
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					g_signal_parse_name ("changing", APP_CENTER_CORE_TYPE_PACKAGE, &_tmp9_, NULL, FALSE);
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					g_signal_handlers_disconnect_matched (_tmp8_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp9_, 0, NULL, (GCallback) _app_center_abstract_app_list_on_package_changing_app_center_core_package_changing, self);
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp10_ = row;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					gtk_widget_destroy ((GtkWidget*) _tmp10_);
#line 85 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_g_object_unref0 (package);
#line 430 "AbstractAppList.c"
				}
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_g_object_unref0 (row);
#line 434 "AbstractAppList.c"
			}
		}
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_g_list_free0 (r_collection);
#line 439 "AbstractAppList.c"
	}
}


void app_center_abstract_app_list_clear (AppCenterAbstractAppList* self) {
#line 82 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 82 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->clear (self);
#line 449 "AbstractAppList.c"
}


static AppCenterWidgetsAppListRow* app_center_abstract_app_list_real_make_row (AppCenterAbstractAppList* self, AppCenterCorePackage* package) {
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_critical ("Type `%s' does not implement abstract method `app_center_abstract_app_list_make_row'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return NULL;
#line 458 "AbstractAppList.c"
}


AppCenterWidgetsAppListRow* app_center_abstract_app_list_make_row (AppCenterAbstractAppList* self, AppCenterCorePackage* package) {
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->make_row (self, package);
#line 467 "AbstractAppList.c"
}


static void app_center_abstract_app_list_real_set_up_row (AppCenterAbstractAppList* self, AppCenterWidgetsAppListRow* row) {
	AppCenterWidgetsAppListRow* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	AppCenterWidgetsAppListRow* _tmp2_ = NULL;
	AppCenterWidgetsAppListRow* _tmp3_ = NULL;
	AppCenterCorePackage* _tmp4_ = NULL;
	AppCenterCorePackage* _tmp5_ = NULL;
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (row != NULL);
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = row;
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = self->list_box;
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp2_ = row;
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_container_add ((GtkContainer*) _tmp1_, (GtkWidget*) _tmp2_);
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp3_ = row;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp4_ = app_center_widgets_app_list_row_get_package (_tmp3_);
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp5_ = _tmp4_;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_signal_connect_object (_tmp5_, "changing", (GCallback) _app_center_abstract_app_list_on_package_changing_app_center_core_package_changing, self, 0);
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (_tmp5_);
#line 500 "AbstractAppList.c"
}


void app_center_abstract_app_list_set_up_row (AppCenterAbstractAppList* self, AppCenterWidgetsAppListRow* row) {
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 95 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->set_up_row (self, row);
#line 509 "AbstractAppList.c"
}


static void app_center_abstract_app_list_real_after_add_remove_change_row (AppCenterAbstractAppList* self) {
}


void app_center_abstract_app_list_after_add_remove_change_row (AppCenterAbstractAppList* self) {
#line 101 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 101 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->after_add_remove_change_row (self);
#line 522 "AbstractAppList.c"
}


static GeeCollection* app_center_abstract_app_list_real_get_packages (AppCenterAbstractAppList* self) {
	GeeCollection* result = NULL;
	GeeTreeSet* tree_set = NULL;
	GeeTreeSet* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = gee_tree_set_new (APP_CENTER_CORE_TYPE_PACKAGE, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	tree_set = _tmp0_;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = self->list_box;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp2_ = gtk_container_get_children ((GtkContainer*) _tmp1_);
#line 540 "AbstractAppList.c"
	{
		GList* r_collection = NULL;
		GList* r_it = NULL;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		r_collection = _tmp2_;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		for (r_it = r_collection; r_it != NULL; r_it = r_it->next) {
#line 548 "AbstractAppList.c"
			GtkWidget* r = NULL;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
			r = (GtkWidget*) r_it->data;
#line 552 "AbstractAppList.c"
			{
				AppCenterWidgetsAppListRow* row = NULL;
				GtkWidget* _tmp3_ = NULL;
				AppCenterWidgetsAppListRow* _tmp4_ = NULL;
				AppCenterWidgetsAppListRow* _tmp5_ = NULL;
				gboolean _tmp6_ = FALSE;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp3_ = r;
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRow));
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				row = _tmp4_;
#line 107 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp5_ = row;
#line 107 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_tmp6_ = app_center_widgets_app_list_row_has_package (_tmp5_);
#line 107 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				if (_tmp6_) {
#line 571 "AbstractAppList.c"
					GeeTreeSet* _tmp7_ = NULL;
					AppCenterWidgetsAppListRow* _tmp8_ = NULL;
					AppCenterCorePackage* _tmp9_ = NULL;
					AppCenterCorePackage* _tmp10_ = NULL;
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp7_ = tree_set;
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp8_ = row;
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp9_ = app_center_widgets_app_list_row_get_package (_tmp8_);
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_tmp10_ = _tmp9_;
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp7_, _tmp10_);
#line 108 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
					_g_object_unref0 (_tmp10_);
#line 588 "AbstractAppList.c"
				}
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
				_g_object_unref0 (row);
#line 592 "AbstractAppList.c"
			}
		}
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_g_list_free0 (r_collection);
#line 597 "AbstractAppList.c"
	}
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	result = (GeeCollection*) tree_set;
#line 112 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return result;
#line 603 "AbstractAppList.c"
}


GeeCollection* app_center_abstract_app_list_get_packages (AppCenterAbstractAppList* self) {
#line 103 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 103 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->get_packages (self);
#line 612 "AbstractAppList.c"
}


static gint app_center_abstract_app_list_real_package_row_compare (AppCenterWidgetsAppListRow* row1, AppCenterWidgetsAppListRow* row2, AppCenterAbstractAppList* self) {
	gint result = 0;
	AppCenterWidgetsAppListRow* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	AppCenterWidgetsAppListRow* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_val_if_fail (row1 != NULL, 0);
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_val_if_fail (row2 != NULL, 0);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = row1;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = app_center_widgets_app_list_row_get_name_label (_tmp0_);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp2_ = _tmp1_;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp3_ = row2;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp4_ = app_center_widgets_app_list_row_get_name_label (_tmp3_);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp5_ = _tmp4_;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp6_ = g_utf8_collate (_tmp2_, _tmp5_);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp7_ = _tmp6_;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_free0 (_tmp5_);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_free0 (_tmp2_);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	result = _tmp7_;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return result;
#line 654 "AbstractAppList.c"
}


gint app_center_abstract_app_list_package_row_compare (AppCenterWidgetsAppListRow* row1, AppCenterWidgetsAppListRow* row2, AppCenterAbstractAppList* self) {
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->package_row_compare (row1, row2, self);
#line 663 "AbstractAppList.c"
}


static void app_center_abstract_app_list_real_on_package_changing (AppCenterAbstractAppList* self, AppCenterCorePackage* package, gboolean is_changing) {
	gboolean _tmp0_ = FALSE;
	guint _tmp3_ = 0U;
	guint _tmp4_ = 0U;
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (package != NULL);
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = is_changing;
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	if (_tmp0_) {
#line 677 "AbstractAppList.c"
		guint _tmp1_ = 0U;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_tmp1_ = self->packages_changing;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		self->packages_changing = _tmp1_ + 1;
#line 683 "AbstractAppList.c"
	} else {
		guint _tmp2_ = 0U;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		_tmp2_ = self->packages_changing;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		self->packages_changing = _tmp2_ - 1;
#line 690 "AbstractAppList.c"
	}
#line 127 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp3_ = self->packages_changing;
#line 127 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_vala_assert (_tmp3_ >= ((guint) 0), "packages_changing >=0");
#line 128 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp4_ = self->packages_changing;
#line 128 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	if (_tmp4_ == ((guint) 0)) {
#line 129 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
		app_center_abstract_app_list_after_add_remove_change_row (self);
#line 702 "AbstractAppList.c"
	}
}


void app_center_abstract_app_list_on_package_changing (AppCenterAbstractAppList* self, AppCenterCorePackage* package, gboolean is_changing) {
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (self != NULL);
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	APP_CENTER_ABSTRACT_APP_LIST_GET_CLASS (self)->on_package_changing (self, package, is_changing);
#line 712 "AbstractAppList.c"
}


AppCenterAbstractAppList* app_center_abstract_app_list_construct (GType object_type) {
	AppCenterAbstractAppList * self = NULL;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self = (AppCenterAbstractAppList*) g_object_new (object_type, NULL);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return self;
#line 722 "AbstractAppList.c"
}


static void _app_center_abstract_app_list___lambda44_ (AppCenterAbstractAppList* self, GtkListBoxRow* r) {
	AppCenterWidgetsAppListRow* row = NULL;
	GtkListBoxRow* _tmp0_ = NULL;
	AppCenterWidgetsAppListRow* _tmp1_ = NULL;
	AppCenterWidgetsAppListRow* _tmp2_ = NULL;
	AppCenterCorePackage* _tmp3_ = NULL;
	AppCenterCorePackage* _tmp4_ = NULL;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_return_if_fail (r != NULL);
#line 43 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = r;
#line 43 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRow));
#line 43 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	row = _tmp1_;
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp2_ = row;
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp3_ = app_center_widgets_app_list_row_get_package (_tmp2_);
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp4_ = _tmp3_;
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_signal_emit_by_name (self, "show-app", _tmp4_);
#line 44 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (_tmp4_);
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (row);
#line 753 "AbstractAppList.c"
}


static void __app_center_abstract_app_list___lambda44__gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self) {
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_app_center_abstract_app_list___lambda44_ ((AppCenterAbstractAppList*) self, row);
#line 760 "AbstractAppList.c"
}


static GObject * app_center_abstract_app_list_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterAbstractAppList * self;
	GtkScrolledWindow* _tmp0_ = NULL;
	GtkScrolledWindow* _tmp1_ = NULL;
	GraniteWidgetsAlertView* alert_view = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GraniteWidgetsAlertView* _tmp4_ = NULL;
	GraniteWidgetsAlertView* _tmp5_ = NULL;
	GtkListBox* _tmp6_ = NULL;
	GtkListBox* _tmp7_ = NULL;
	GtkListBox* _tmp8_ = NULL;
	GtkListBox* _tmp9_ = NULL;
	GraniteWidgetsAlertView* _tmp10_ = NULL;
	GtkListBox* _tmp11_ = NULL;
	GtkListBox* _tmp12_ = NULL;
	GtkScrolledWindow* _tmp13_ = NULL;
	GtkListBox* _tmp14_ = NULL;
	GtkSizeGroup* _tmp15_ = NULL;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	parent_class = G_OBJECT_CLASS (app_center_abstract_app_list_parent_class);
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_TYPE_ABSTRACT_APP_LIST, AppCenterAbstractAppList);
#line 30 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp0_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_object_ref_sink (_tmp0_);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (self->scrolled);
#line 32 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self->scrolled = _tmp0_;
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp1_ = self->scrolled;
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_object_set (_tmp1_, "hscrollbar-policy", GTK_POLICY_NEVER, NULL);
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp2_ = _ ("No Results");
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp3_ = _ ("No apps could be found. Try changing search terms.");
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp4_ = granite_widgets_alert_view_new (_tmp2_, _tmp3_, "edit-find-symbolic");
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_object_ref_sink (_tmp4_);
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	alert_view = _tmp4_;
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp5_ = alert_view;
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp5_);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp6_ = (GtkListBox*) gtk_list_box_new ();
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_object_ref_sink (_tmp6_);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (self->list_box);
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self->list_box = _tmp6_;
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp7_ = self->list_box;
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_object_set ((GtkWidget*) _tmp7_, "expand", TRUE, NULL);
#line 39 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp8_ = self->list_box;
#line 39 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_list_box_set_activate_on_single_click (_tmp8_, TRUE);
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp9_ = self->list_box;
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp10_ = alert_view;
#line 40 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_list_box_set_placeholder (_tmp9_, (GtkWidget*) _tmp10_);
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp11_ = self->list_box;
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_list_box_set_sort_func (_tmp11_, (GtkListBoxSortFunc) app_center_abstract_app_list_package_row_compare, g_object_ref (self), g_object_unref);
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp12_ = self->list_box;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_signal_connect_object (_tmp12_, "row-activated", (GCallback) __app_center_abstract_app_list___lambda44__gtk_list_box_row_activated, self, 0);
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp13_ = self->scrolled;
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp14_ = self->list_box;
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	gtk_container_add ((GtkContainer*) _tmp13_, (GtkWidget*) _tmp14_);
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_tmp15_ = gtk_size_group_new (GTK_SIZE_GROUP_BOTH);
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (self->action_button_group);
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self->action_button_group = _tmp15_;
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (alert_view);
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	return obj;
#line 865 "AbstractAppList.c"
}


static void app_center_abstract_app_list_class_init (AppCenterAbstractAppListClass * klass) {
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	app_center_abstract_app_list_parent_class = g_type_class_peek_parent (klass);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->add_packages = (void (*)(AppCenterAbstractAppList*, GeeCollection*)) app_center_abstract_app_list_real_add_packages;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->add_package = (void (*)(AppCenterAbstractAppList*, AppCenterCorePackage*)) app_center_abstract_app_list_real_add_package;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->clear = (void (*)(AppCenterAbstractAppList*)) app_center_abstract_app_list_real_clear;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->make_row = (AppCenterWidgetsAppListRow* (*)(AppCenterAbstractAppList*, AppCenterCorePackage*)) app_center_abstract_app_list_real_make_row;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->set_up_row = (void (*)(AppCenterAbstractAppList*, AppCenterWidgetsAppListRow*)) app_center_abstract_app_list_real_set_up_row;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->after_add_remove_change_row = (void (*)(AppCenterAbstractAppList*)) app_center_abstract_app_list_real_after_add_remove_change_row;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->get_packages = (GeeCollection* (*)(AppCenterAbstractAppList*)) app_center_abstract_app_list_real_get_packages;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->package_row_compare = (gint (*)(AppCenterAbstractAppList*, AppCenterWidgetsAppListRow*, AppCenterAbstractAppList*)) app_center_abstract_app_list_real_package_row_compare;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	((AppCenterAbstractAppListClass *) klass)->on_package_changing = (void (*)(AppCenterAbstractAppList*, AppCenterCorePackage*, gboolean)) app_center_abstract_app_list_real_on_package_changing;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_abstract_app_list_constructor;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	G_OBJECT_CLASS (klass)->finalize = app_center_abstract_app_list_finalize;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	g_signal_new ("show_app", APP_CENTER_TYPE_ABSTRACT_APP_LIST, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, APP_CENTER_CORE_TYPE_PACKAGE);
#line 896 "AbstractAppList.c"
}


static void app_center_abstract_app_list_instance_init (AppCenterAbstractAppList * self) {
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self->packages_changing = (guint) 0;
#line 903 "AbstractAppList.c"
}


static void app_center_abstract_app_list_finalize (GObject* obj) {
	AppCenterAbstractAppList * self;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_TYPE_ABSTRACT_APP_LIST, AppCenterAbstractAppList);
#line 24 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (self->scrolled);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (self->list_box);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	_g_object_unref0 (self->action_button_group);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/AbstractAppList.vala"
	G_OBJECT_CLASS (app_center_abstract_app_list_parent_class)->finalize (obj);
#line 919 "AbstractAppList.c"
}


GType app_center_abstract_app_list_get_type (void) {
	static volatile gsize app_center_abstract_app_list_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_abstract_app_list_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterAbstractAppListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_abstract_app_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterAbstractAppList), 0, (GInstanceInitFunc) app_center_abstract_app_list_instance_init, NULL };
		GType app_center_abstract_app_list_type_id;
		app_center_abstract_app_list_type_id = g_type_register_static (gtk_box_get_type (), "AppCenterAbstractAppList", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&app_center_abstract_app_list_type_id__volatile, app_center_abstract_app_list_type_id);
	}
	return app_center_abstract_app_list_type_id__volatile;
}



