/* PackageRow.c generated by valac 0.34.8, the Vala compiler
 * generated from PackageRow.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2014-2016 elementary LLC. (https://elementary.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: Corentin Noël <corentin@elementary.io>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <pango/pango.h>
#include <packagekit-glib2/packagekit.h>


#define APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW (app_center_widgets_app_list_row_get_type ())
#define APP_CENTER_WIDGETS_APP_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRow))
#define APP_CENTER_WIDGETS_IS_APP_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW))
#define APP_CENTER_WIDGETS_APP_LIST_ROW_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, AppCenterWidgetsAppListRowIface))

typedef struct _AppCenterWidgetsAppListRow AppCenterWidgetsAppListRow;
typedef struct _AppCenterWidgetsAppListRowIface AppCenterWidgetsAppListRowIface;

#define APP_CENTER_CORE_TYPE_PACKAGE (app_center_core_package_get_type ())
#define APP_CENTER_CORE_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackage))
#define APP_CENTER_CORE_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))
#define APP_CENTER_CORE_IS_PACKAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_IS_PACKAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_PACKAGE))
#define APP_CENTER_CORE_PACKAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_PACKAGE, AppCenterCorePackageClass))

typedef struct _AppCenterCorePackage AppCenterCorePackage;
typedef struct _AppCenterCorePackageClass AppCenterCorePackageClass;

#define APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW (app_center_widgets_package_row_get_type ())
#define APP_CENTER_WIDGETS_PACKAGE_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, AppCenterWidgetsPackageRow))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, AppCenterWidgetsPackageRowClass))
#define APP_CENTER_WIDGETS_IS_PACKAGE_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW))
#define APP_CENTER_WIDGETS_IS_PACKAGE_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, AppCenterWidgetsPackageRowClass))

typedef struct _AppCenterWidgetsPackageRow AppCenterWidgetsPackageRow;
typedef struct _AppCenterWidgetsPackageRowClass AppCenterWidgetsPackageRowClass;
typedef struct _AppCenterWidgetsPackageRowPrivate AppCenterWidgetsPackageRowPrivate;

#define APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER (app_center_abstract_app_container_get_type ())
#define APP_CENTER_ABSTRACT_APP_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER, AppCenterAbstractAppContainer))
#define APP_CENTER_ABSTRACT_APP_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER, AppCenterAbstractAppContainerClass))
#define APP_CENTER_IS_ABSTRACT_APP_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER))
#define APP_CENTER_IS_ABSTRACT_APP_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER))
#define APP_CENTER_ABSTRACT_APP_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER, AppCenterAbstractAppContainerClass))

typedef struct _AppCenterAbstractAppContainer AppCenterAbstractAppContainer;
typedef struct _AppCenterAbstractAppContainerClass AppCenterAbstractAppContainerClass;

#define APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID (app_center_widgets_package_row_abstract_package_row_grid_get_type ())
#define APP_CENTER_WIDGETS_PACKAGE_ROW_ABSTRACT_PACKAGE_ROW_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGrid))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_ABSTRACT_PACKAGE_ROW_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGridClass))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_IS_ABSTRACT_PACKAGE_ROW_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_IS_ABSTRACT_PACKAGE_ROW_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_ABSTRACT_PACKAGE_ROW_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGridClass))

typedef struct _AppCenterWidgetsPackageRowAbstractPackageRowGrid AppCenterWidgetsPackageRowAbstractPackageRowGrid;
typedef struct _AppCenterWidgetsPackageRowAbstractPackageRowGridClass AppCenterWidgetsPackageRowAbstractPackageRowGridClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID (app_center_widgets_package_row_installed_package_row_grid_get_type ())
#define APP_CENTER_WIDGETS_PACKAGE_ROW_INSTALLED_PACKAGE_ROW_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowInstalledPackageRowGrid))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_INSTALLED_PACKAGE_ROW_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowInstalledPackageRowGridClass))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_IS_INSTALLED_PACKAGE_ROW_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_IS_INSTALLED_PACKAGE_ROW_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_INSTALLED_PACKAGE_ROW_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowInstalledPackageRowGridClass))

typedef struct _AppCenterWidgetsPackageRowInstalledPackageRowGrid AppCenterWidgetsPackageRowInstalledPackageRowGrid;
typedef struct _AppCenterWidgetsPackageRowInstalledPackageRowGridClass AppCenterWidgetsPackageRowInstalledPackageRowGridClass;

#define APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID (app_center_widgets_package_row_list_package_row_grid_get_type ())
#define APP_CENTER_WIDGETS_PACKAGE_ROW_LIST_PACKAGE_ROW_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowListPackageRowGrid))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_LIST_PACKAGE_ROW_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowListPackageRowGridClass))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_IS_LIST_PACKAGE_ROW_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_IS_LIST_PACKAGE_ROW_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID))
#define APP_CENTER_WIDGETS_PACKAGE_ROW_LIST_PACKAGE_ROW_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowListPackageRowGridClass))

typedef struct _AppCenterWidgetsPackageRowListPackageRowGrid AppCenterWidgetsPackageRowListPackageRowGrid;
typedef struct _AppCenterWidgetsPackageRowListPackageRowGridClass AppCenterWidgetsPackageRowListPackageRowGridClass;
typedef struct _AppCenterAbstractAppContainerPrivate AppCenterAbstractAppContainerPrivate;

#define APP_CENTER_WIDGETS_TYPE_HUMBLE_BUTTON (app_center_widgets_humble_button_get_type ())
#define APP_CENTER_WIDGETS_HUMBLE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_HUMBLE_BUTTON, AppCenterWidgetsHumbleButton))
#define APP_CENTER_WIDGETS_HUMBLE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_TYPE_HUMBLE_BUTTON, AppCenterWidgetsHumbleButtonClass))
#define APP_CENTER_WIDGETS_IS_HUMBLE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_HUMBLE_BUTTON))
#define APP_CENTER_WIDGETS_IS_HUMBLE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_TYPE_HUMBLE_BUTTON))
#define APP_CENTER_WIDGETS_HUMBLE_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_TYPE_HUMBLE_BUTTON, AppCenterWidgetsHumbleButtonClass))

typedef struct _AppCenterWidgetsHumbleButton AppCenterWidgetsHumbleButton;
typedef struct _AppCenterWidgetsHumbleButtonClass AppCenterWidgetsHumbleButtonClass;
typedef struct _AppCenterWidgetsPackageRowAbstractPackageRowGridPrivate AppCenterWidgetsPackageRowAbstractPackageRowGridPrivate;
typedef struct _AppCenterWidgetsPackageRowInstalledPackageRowGridPrivate AppCenterWidgetsPackageRowInstalledPackageRowGridPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define APP_CENTER_CORE_TYPE_CHANGE_INFORMATION (app_center_core_change_information_get_type ())
#define APP_CENTER_CORE_CHANGE_INFORMATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformation))
#define APP_CENTER_CORE_CHANGE_INFORMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformationClass))
#define APP_CENTER_CORE_IS_CHANGE_INFORMATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION))
#define APP_CENTER_CORE_IS_CHANGE_INFORMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION))
#define APP_CENTER_CORE_CHANGE_INFORMATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_CORE_TYPE_CHANGE_INFORMATION, AppCenterCoreChangeInformationClass))

typedef struct _AppCenterCoreChangeInformation AppCenterCoreChangeInformation;
typedef struct _AppCenterCoreChangeInformationClass AppCenterCoreChangeInformationClass;
typedef struct _AppCenterWidgetsPackageRowListPackageRowGridPrivate AppCenterWidgetsPackageRowListPackageRowGridPrivate;

struct _AppCenterWidgetsAppListRowIface {
	GTypeInterface parent_iface;
	gboolean (*get_update_available) (AppCenterWidgetsAppListRow* self);
	gboolean (*get_is_os_updates) (AppCenterWidgetsAppListRow* self);
	gboolean (*get_is_driver) (AppCenterWidgetsAppListRow* self);
	gboolean (*get_is_updating) (AppCenterWidgetsAppListRow* self);
	gchar* (*get_name_label) (AppCenterWidgetsAppListRow* self);
	gboolean (*has_package) (AppCenterWidgetsAppListRow* self);
	AppCenterCorePackage* (*get_package) (AppCenterWidgetsAppListRow* self);
};

struct _AppCenterWidgetsPackageRow {
	GtkListBoxRow parent_instance;
	AppCenterWidgetsPackageRowPrivate * priv;
};

struct _AppCenterWidgetsPackageRowClass {
	GtkListBoxRowClass parent_class;
};

struct _AppCenterWidgetsPackageRowPrivate {
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* grid;
};

struct _AppCenterAbstractAppContainer {
	GtkGrid parent_instance;
	AppCenterAbstractAppContainerPrivate * priv;
	GtkImage* image;
	GtkLabel* package_name;
	GtkLabel* package_author;
	GtkLabel* package_summary;
	AppCenterWidgetsHumbleButton* action_button;
	GtkButton* uninstall_button;
	GtkButton* open_button;
	GtkProgressBar* progress_bar;
	GtkButton* cancel_button;
	GtkSizeGroup* action_button_group;
	GtkStack* action_stack;
	gboolean show_uninstall;
	gboolean show_open;
	gboolean updates_view;
};

struct _AppCenterAbstractAppContainerClass {
	GtkGridClass parent_class;
	void (*set_up_package) (AppCenterAbstractAppContainer* self, guint icon_size);
	void (*update_state) (AppCenterAbstractAppContainer* self, gboolean first_update);
	void (*update_progress_status) (AppCenterAbstractAppContainer* self);
};

struct _AppCenterWidgetsPackageRowAbstractPackageRowGrid {
	AppCenterAbstractAppContainer parent_instance;
	AppCenterWidgetsPackageRowAbstractPackageRowGridPrivate * priv;
};

struct _AppCenterWidgetsPackageRowAbstractPackageRowGridClass {
	AppCenterAbstractAppContainerClass parent_class;
};

struct _AppCenterWidgetsPackageRowInstalledPackageRowGrid {
	AppCenterWidgetsPackageRowAbstractPackageRowGrid parent_instance;
	AppCenterWidgetsPackageRowInstalledPackageRowGridPrivate * priv;
};

struct _AppCenterWidgetsPackageRowInstalledPackageRowGridClass {
	AppCenterWidgetsPackageRowAbstractPackageRowGridClass parent_class;
};

struct _AppCenterWidgetsPackageRowInstalledPackageRowGridPrivate {
	GtkLabel* app_version;
};

struct _AppCenterWidgetsPackageRowListPackageRowGrid {
	AppCenterWidgetsPackageRowAbstractPackageRowGrid parent_instance;
	AppCenterWidgetsPackageRowListPackageRowGridPrivate * priv;
};

struct _AppCenterWidgetsPackageRowListPackageRowGridClass {
	AppCenterWidgetsPackageRowAbstractPackageRowGridClass parent_class;
};


static gpointer app_center_widgets_package_row_parent_class = NULL;
static gpointer app_center_widgets_package_row_abstract_package_row_grid_parent_class = NULL;
static gpointer app_center_widgets_package_row_installed_package_row_grid_parent_class = NULL;
static gpointer app_center_widgets_package_row_list_package_row_grid_parent_class = NULL;
static AppCenterWidgetsAppListRowIface* app_center_widgets_package_row_app_center_widgets_app_list_row_parent_iface = NULL;

GType app_center_core_package_get_type (void) G_GNUC_CONST;
GType app_center_widgets_app_list_row_get_type (void) G_GNUC_CONST;
GType app_center_widgets_package_row_get_type (void) G_GNUC_CONST;
GType app_center_abstract_app_container_get_type (void) G_GNUC_CONST;
static GType app_center_widgets_package_row_abstract_package_row_grid_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
#define APP_CENTER_WIDGETS_PACKAGE_ROW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, AppCenterWidgetsPackageRowPrivate))
enum  {
	APP_CENTER_WIDGETS_PACKAGE_ROW_DUMMY_PROPERTY
};
AppCenterWidgetsPackageRow* app_center_widgets_package_row_new_installed (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
AppCenterWidgetsPackageRow* app_center_widgets_package_row_construct_installed (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
static AppCenterWidgetsPackageRowInstalledPackageRowGrid* app_center_widgets_package_row_installed_package_row_grid_new (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
static AppCenterWidgetsPackageRowInstalledPackageRowGrid* app_center_widgets_package_row_installed_package_row_grid_construct (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
static GType app_center_widgets_package_row_installed_package_row_grid_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static void __lambda45_ (AppCenterWidgetsPackageRow* self);
static void ___lambda45__app_center_widgets_package_row_abstract_package_row_grid_changed (AppCenterWidgetsPackageRowAbstractPackageRowGrid* _sender, gpointer self);
AppCenterWidgetsPackageRow* app_center_widgets_package_row_new_list (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
AppCenterWidgetsPackageRow* app_center_widgets_package_row_construct_list (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
static AppCenterWidgetsPackageRowListPackageRowGrid* app_center_widgets_package_row_list_package_row_grid_new (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
static AppCenterWidgetsPackageRowListPackageRowGrid* app_center_widgets_package_row_list_package_row_grid_construct (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
static GType app_center_widgets_package_row_list_package_row_grid_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static void __lambda46_ (AppCenterWidgetsPackageRow* self);
static void ___lambda46__app_center_widgets_package_row_abstract_package_row_grid_changed (AppCenterWidgetsPackageRowAbstractPackageRowGrid* _sender, gpointer self);
static gboolean app_center_widgets_package_row_real_get_update_available (AppCenterWidgetsAppListRow* base);
gboolean app_center_abstract_app_container_get_update_available (AppCenterAbstractAppContainer* self);
static gboolean app_center_widgets_package_row_real_get_is_driver (AppCenterWidgetsAppListRow* base);
gboolean app_center_abstract_app_container_get_is_driver (AppCenterAbstractAppContainer* self);
static gboolean app_center_widgets_package_row_real_get_is_updating (AppCenterWidgetsAppListRow* base);
gboolean app_center_abstract_app_container_get_is_updating (AppCenterAbstractAppContainer* self);
static gboolean app_center_widgets_package_row_real_get_is_os_updates (AppCenterWidgetsAppListRow* base);
gboolean app_center_abstract_app_container_get_is_os_updates (AppCenterAbstractAppContainer* self);
static gchar* app_center_widgets_package_row_real_get_name_label (AppCenterWidgetsAppListRow* base);
const gchar* app_center_abstract_app_container_get_name_label (AppCenterAbstractAppContainer* self);
static AppCenterCorePackage* app_center_widgets_package_row_real_get_package (AppCenterWidgetsAppListRow* base);
AppCenterCorePackage* app_center_abstract_app_container_get_package (AppCenterAbstractAppContainer* self);
void app_center_widgets_package_row_set_action_sensitive (AppCenterWidgetsPackageRow* self, gboolean is_sensitive);
void app_center_abstract_app_container_set_action_sensitive (AppCenterAbstractAppContainer* self, gboolean value);
static gboolean app_center_widgets_package_row_real_has_package (AppCenterWidgetsAppListRow* base);
AppCenterWidgetsPackageRow* app_center_widgets_package_row_new (void);
AppCenterWidgetsPackageRow* app_center_widgets_package_row_construct (GType object_type);
GType app_center_widgets_humble_button_get_type (void) G_GNUC_CONST;
enum  {
	APP_CENTER_WIDGETS_PACKAGE_ROW_ABSTRACT_PACKAGE_ROW_GRID_DUMMY_PROPERTY
};
static AppCenterWidgetsPackageRowAbstractPackageRowGrid* app_center_widgets_package_row_abstract_package_row_grid_construct (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall);
AppCenterAbstractAppContainer* app_center_abstract_app_container_construct (GType object_type);
void app_center_abstract_app_container_set_package (AppCenterAbstractAppContainer* self, AppCenterCorePackage* value);
static GObject * app_center_widgets_package_row_abstract_package_row_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
#define APP_CENTER_WIDGETS_PACKAGE_ROW_INSTALLED_PACKAGE_ROW_GRID_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowInstalledPackageRowGridPrivate))
enum  {
	APP_CENTER_WIDGETS_PACKAGE_ROW_INSTALLED_PACKAGE_ROW_GRID_DUMMY_PROPERTY
};
void app_center_abstract_app_container_set_up_package (AppCenterAbstractAppContainer* self, guint icon_size);
static void app_center_widgets_package_row_installed_package_row_grid_real_set_up_package (AppCenterAbstractAppContainer* base, guint icon_size);
gchar* app_center_core_package_get_version (AppCenterCorePackage* self);
static void app_center_widgets_package_row_installed_package_row_grid_real_update_state (AppCenterAbstractAppContainer* base, gboolean first_update);
void app_center_abstract_app_container_update_action (AppCenterAbstractAppContainer* self);
static void app_center_widgets_package_row_installed_package_row_grid_real_update_progress_status (AppCenterAbstractAppContainer* base);
void app_center_abstract_app_container_update_progress_status (AppCenterAbstractAppContainer* self);
GType app_center_core_change_information_get_type (void) G_GNUC_CONST;
AppCenterCoreChangeInformation* app_center_core_package_get_change_information (AppCenterCorePackage* self);
PkStatusEnum app_center_core_change_information_get_status (AppCenterCoreChangeInformation* self);
static GObject * app_center_widgets_package_row_installed_package_row_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void app_center_widgets_package_row_installed_package_row_grid_finalize (GObject* obj);
enum  {
	APP_CENTER_WIDGETS_PACKAGE_ROW_LIST_PACKAGE_ROW_GRID_DUMMY_PROPERTY
};
static void app_center_widgets_package_row_list_package_row_grid_real_set_up_package (AppCenterAbstractAppContainer* base, guint icon_size);
gchar* app_center_core_package_get_summary (AppCenterCorePackage* self);
static GObject * app_center_widgets_package_row_list_package_row_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void app_center_widgets_package_row_finalize (GObject* obj);


static void __lambda45_ (AppCenterWidgetsPackageRow* self) {
#line 29 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_list_box_row_changed ((GtkListBoxRow*) self);
#line 295 "PackageRow.c"
}


static void ___lambda45__app_center_widgets_package_row_abstract_package_row_grid_changed (AppCenterWidgetsPackageRowAbstractPackageRowGrid* _sender, gpointer self) {
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	__lambda45_ ((AppCenterWidgetsPackageRow*) self);
#line 302 "PackageRow.c"
}


AppCenterWidgetsPackageRow* app_center_widgets_package_row_construct_installed (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
	AppCenterWidgetsPackageRow * self = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	GtkSizeGroup* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	AppCenterWidgetsPackageRowInstalledPackageRowGrid* _tmp3_ = NULL;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp4_ = NULL;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp5_ = NULL;
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_return_val_if_fail (package != NULL, NULL);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) g_object_new (object_type, NULL);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = package;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = size_group;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = show_uninstall;
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = app_center_widgets_package_row_installed_package_row_grid_new (_tmp0_, _tmp1_, _tmp2_);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_ref_sink (_tmp3_);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_object_unref0 (self->priv->grid);
#line 26 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self->priv->grid = (AppCenterWidgetsPackageRowAbstractPackageRowGrid*) _tmp3_;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = self->priv->grid;
#line 27 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = self->priv->grid;
#line 28 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_signal_connect_object (_tmp5_, "changed", (GCallback) ___lambda45__app_center_widgets_package_row_abstract_package_row_grid_changed, self, 0);
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self;
#line 342 "PackageRow.c"
}


AppCenterWidgetsPackageRow* app_center_widgets_package_row_new_installed (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
#line 25 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return app_center_widgets_package_row_construct_installed (APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, package, size_group, show_uninstall);
#line 349 "PackageRow.c"
}


static void __lambda46_ (AppCenterWidgetsPackageRow* self) {
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_list_box_row_changed ((GtkListBoxRow*) self);
#line 356 "PackageRow.c"
}


static void ___lambda46__app_center_widgets_package_row_abstract_package_row_grid_changed (AppCenterWidgetsPackageRowAbstractPackageRowGrid* _sender, gpointer self) {
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	__lambda46_ ((AppCenterWidgetsPackageRow*) self);
#line 363 "PackageRow.c"
}


AppCenterWidgetsPackageRow* app_center_widgets_package_row_construct_list (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
	AppCenterWidgetsPackageRow * self = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	GtkSizeGroup* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	AppCenterWidgetsPackageRowListPackageRowGrid* _tmp3_ = NULL;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp4_ = NULL;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp5_ = NULL;
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_return_val_if_fail (package != NULL, NULL);
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) g_object_new (object_type, NULL);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = package;
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = size_group;
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = show_uninstall;
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = app_center_widgets_package_row_list_package_row_grid_new (_tmp0_, _tmp1_, _tmp2_);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_ref_sink (_tmp3_);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_object_unref0 (self->priv->grid);
#line 34 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self->priv->grid = (AppCenterWidgetsPackageRowAbstractPackageRowGrid*) _tmp3_;
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = self->priv->grid;
#line 35 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = self->priv->grid;
#line 36 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_signal_connect_object (_tmp5_, "changed", (GCallback) ___lambda46__app_center_widgets_package_row_abstract_package_row_grid_changed, self, 0);
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self;
#line 403 "PackageRow.c"
}


AppCenterWidgetsPackageRow* app_center_widgets_package_row_new_list (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
#line 33 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return app_center_widgets_package_row_construct_list (APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, package, size_group, show_uninstall);
#line 410 "PackageRow.c"
}


static gboolean app_center_widgets_package_row_real_get_update_available (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	gboolean result = FALSE;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 41 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_update_available ((AppCenterAbstractAppContainer*) _tmp0_);
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = _tmp2_;
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 432 "PackageRow.c"
}


static gboolean app_center_widgets_package_row_real_get_is_driver (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	gboolean result = FALSE;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 45 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_is_driver ((AppCenterAbstractAppContainer*) _tmp0_);
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = _tmp2_;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 454 "PackageRow.c"
}


static gboolean app_center_widgets_package_row_real_get_is_updating (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	gboolean result = FALSE;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_is_updating ((AppCenterAbstractAppContainer*) _tmp0_);
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = _tmp2_;
#line 50 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 476 "PackageRow.c"
}


static gboolean app_center_widgets_package_row_real_get_is_os_updates (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	gboolean result = FALSE;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_is_os_updates ((AppCenterAbstractAppContainer*) _tmp0_);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = _tmp2_;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 498 "PackageRow.c"
}


static gchar* app_center_widgets_package_row_real_get_name_label (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	gchar* result = NULL;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 57 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_name_label ((AppCenterAbstractAppContainer*) _tmp0_);
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = _tmp3_;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 523 "PackageRow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self ? g_object_ref (self) : NULL;
#line 530 "PackageRow.c"
}


static AppCenterCorePackage* app_center_widgets_package_row_real_get_package (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	AppCenterCorePackage* result = NULL;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	AppCenterCorePackage* _tmp1_ = NULL;
	AppCenterCorePackage* _tmp2_ = NULL;
	AppCenterCorePackage* _tmp3_ = NULL;
#line 61 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_package ((AppCenterAbstractAppContainer*) _tmp0_);
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = _tmp3_;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 555 "PackageRow.c"
}


void app_center_widgets_package_row_set_action_sensitive (AppCenterWidgetsPackageRow* self, gboolean is_sensitive) {
	AppCenterWidgetsPackageRowAbstractPackageRowGrid* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 65 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_return_if_fail (self != NULL);
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->grid;
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = is_sensitive;
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_abstract_app_container_set_action_sensitive ((AppCenterAbstractAppContainer*) _tmp0_, _tmp1_);
#line 570 "PackageRow.c"
}


static gboolean app_center_widgets_package_row_real_has_package (AppCenterWidgetsAppListRow* base) {
	AppCenterWidgetsPackageRow * self;
	gboolean result = FALSE;
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) base;
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	result = TRUE;
#line 70 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return result;
#line 583 "PackageRow.c"
}


AppCenterWidgetsPackageRow* app_center_widgets_package_row_construct (GType object_type) {
	AppCenterWidgetsPackageRow * self = NULL;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRow*) g_object_new (object_type, NULL);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self;
#line 593 "PackageRow.c"
}


AppCenterWidgetsPackageRow* app_center_widgets_package_row_new (void) {
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return app_center_widgets_package_row_construct (APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW);
#line 600 "PackageRow.c"
}


static AppCenterWidgetsPackageRowAbstractPackageRowGrid* app_center_widgets_package_row_abstract_package_row_grid_construct (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
	AppCenterWidgetsPackageRowAbstractPackageRowGrid * self = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	GtkSizeGroup* _tmp2_ = NULL;
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_return_val_if_fail (package != NULL, NULL);
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowAbstractPackageRowGrid*) app_center_abstract_app_container_construct (object_type);
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = package;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_abstract_app_container_set_package ((AppCenterAbstractAppContainer*) self, _tmp0_);
#line 99 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = show_uninstall;
#line 99 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainer*) self)->show_uninstall = _tmp1_;
#line 100 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainer*) self)->show_open = FALSE;
#line 102 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = size_group;
#line 102 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	if (_tmp2_ != NULL) {
#line 627 "PackageRow.c"
		GtkSizeGroup* _tmp3_ = NULL;
		AppCenterWidgetsHumbleButton* _tmp4_ = NULL;
		GtkSizeGroup* _tmp5_ = NULL;
		GtkButton* _tmp6_ = NULL;
		GtkSizeGroup* _tmp7_ = NULL;
		GtkButton* _tmp8_ = NULL;
#line 103 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp3_ = size_group;
#line 103 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp4_ = ((AppCenterAbstractAppContainer*) self)->action_button;
#line 103 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		gtk_size_group_add_widget (_tmp3_, (GtkWidget*) _tmp4_);
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp5_ = size_group;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp6_ = ((AppCenterAbstractAppContainer*) self)->cancel_button;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		gtk_size_group_add_widget (_tmp5_, (GtkWidget*) _tmp6_);
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp7_ = size_group;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp8_ = ((AppCenterAbstractAppContainer*) self)->uninstall_button;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		gtk_size_group_add_widget (_tmp7_, (GtkWidget*) _tmp8_);
#line 652 "PackageRow.c"
	}
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self;
#line 656 "PackageRow.c"
}


static GObject * app_center_widgets_package_row_abstract_package_row_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterWidgetsPackageRowAbstractPackageRowGrid * self;
	GtkImage* _tmp0_ = NULL;
	GtkImage* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkStyleContext* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkImage* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkStack* _tmp9_ = NULL;
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	parent_class = G_OBJECT_CLASS (app_center_widgets_package_row_abstract_package_row_grid_parent_class);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGrid);
#line 77 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_set ((GtkWidget*) self, "margin", 6, NULL);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_margin_start ((GtkWidget*) self, 12);
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_margin_end ((GtkWidget*) self, 12);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_set_column_spacing ((GtkGrid*) self, 12);
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_set_row_spacing ((GtkGrid*) self, 6);
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = ((AppCenterAbstractAppContainer*) self)->image;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_set (_tmp0_, "icon-size", (gint) GTK_ICON_SIZE_DIALOG, NULL);
#line 85 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = ((AppCenterAbstractAppContainer*) self)->image;
#line 85 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_image_set_pixel_size (_tmp1_, 48);
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = ((AppCenterAbstractAppContainer*) self)->package_name;
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_style_context_add_class (_tmp3_, "h3");
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = ((AppCenterAbstractAppContainer*) self)->package_name;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp4_, TRUE);
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = ((AppCenterAbstractAppContainer*) self)->package_name;
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp5_, GTK_ALIGN_END);
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp6_ = ((AppCenterAbstractAppContainer*) self)->package_name;
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_set (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, gtk_misc_get_type (), GtkMisc), "xalign", (gfloat) 0, NULL);
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp7_ = ((AppCenterAbstractAppContainer*) self)->image;
#line 92 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp7_, 0, 0, 1, 2);
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp8_ = ((AppCenterAbstractAppContainer*) self)->package_name;
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp8_, 1, 0, 1, 1);
#line 94 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp9_ = ((AppCenterAbstractAppContainer*) self)->action_stack;
#line 94 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp9_, 2, 0, 1, 2);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return obj;
#line 730 "PackageRow.c"
}


static void app_center_widgets_package_row_abstract_package_row_grid_class_init (AppCenterWidgetsPackageRowAbstractPackageRowGridClass * klass) {
#line 73 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_widgets_package_row_abstract_package_row_grid_parent_class = g_type_class_peek_parent (klass);
#line 73 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_widgets_package_row_abstract_package_row_grid_constructor;
#line 73 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_signal_new ("changed", APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 741 "PackageRow.c"
}


static void app_center_widgets_package_row_abstract_package_row_grid_instance_init (AppCenterWidgetsPackageRowAbstractPackageRowGrid * self) {
}


static GType app_center_widgets_package_row_abstract_package_row_grid_get_type (void) {
	static volatile gsize app_center_widgets_package_row_abstract_package_row_grid_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_widgets_package_row_abstract_package_row_grid_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterWidgetsPackageRowAbstractPackageRowGridClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_widgets_package_row_abstract_package_row_grid_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterWidgetsPackageRowAbstractPackageRowGrid), 0, (GInstanceInitFunc) app_center_widgets_package_row_abstract_package_row_grid_instance_init, NULL };
		GType app_center_widgets_package_row_abstract_package_row_grid_type_id;
		app_center_widgets_package_row_abstract_package_row_grid_type_id = g_type_register_static (APP_CENTER_TYPE_ABSTRACT_APP_CONTAINER, "AppCenterWidgetsPackageRowAbstractPackageRowGrid", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&app_center_widgets_package_row_abstract_package_row_grid_type_id__volatile, app_center_widgets_package_row_abstract_package_row_grid_type_id);
	}
	return app_center_widgets_package_row_abstract_package_row_grid_type_id__volatile;
}


static AppCenterWidgetsPackageRowInstalledPackageRowGrid* app_center_widgets_package_row_installed_package_row_grid_construct (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
	AppCenterWidgetsPackageRowInstalledPackageRowGrid * self = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	GtkSizeGroup* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_return_val_if_fail (package != NULL, NULL);
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = package;
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = size_group;
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = show_uninstall;
#line 125 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowInstalledPackageRowGrid*) app_center_widgets_package_row_abstract_package_row_grid_construct (object_type, _tmp0_, _tmp1_, _tmp2_);
#line 126 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_abstract_app_container_set_up_package ((AppCenterAbstractAppContainer*) self, (guint) 48);
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self;
#line 780 "PackageRow.c"
}


static AppCenterWidgetsPackageRowInstalledPackageRowGrid* app_center_widgets_package_row_installed_package_row_grid_new (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
#line 124 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return app_center_widgets_package_row_installed_package_row_grid_construct (APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, package, size_group, show_uninstall);
#line 787 "PackageRow.c"
}


static void app_center_widgets_package_row_installed_package_row_grid_real_set_up_package (AppCenterAbstractAppContainer* base, guint icon_size) {
	AppCenterWidgetsPackageRowInstalledPackageRowGrid * self;
	GtkLabel* _tmp0_ = NULL;
	AppCenterCorePackage* _tmp1_ = NULL;
	AppCenterCorePackage* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	guint _tmp6_ = 0U;
#line 129 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowInstalledPackageRowGrid*) base;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = self->priv->app_version;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_package ((AppCenterAbstractAppContainer*) self);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = app_center_core_package_get_version (_tmp2_);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = _tmp3_;
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_label_set_label (_tmp0_, _tmp4_);
#line 130 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_free0 (_tmp4_);
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = self->priv->app_version;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_label_set_ellipsize (_tmp5_, PANGO_ELLIPSIZE_END);
#line 133 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp6_ = icon_size;
#line 133 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	APP_CENTER_ABSTRACT_APP_CONTAINER_CLASS (app_center_widgets_package_row_installed_package_row_grid_parent_class)->set_up_package ((AppCenterAbstractAppContainer*) G_TYPE_CHECK_INSTANCE_CAST (self, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGrid), _tmp6_);
#line 824 "PackageRow.c"
}


static void app_center_widgets_package_row_installed_package_row_grid_real_update_state (AppCenterAbstractAppContainer* base, gboolean first_update) {
	AppCenterWidgetsPackageRowInstalledPackageRowGrid * self;
	gboolean _tmp0_ = FALSE;
#line 136 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowInstalledPackageRowGrid*) base;
#line 137 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = first_update;
#line 137 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	if (!_tmp0_) {
#line 837 "PackageRow.c"
		GtkLabel* _tmp1_ = NULL;
		AppCenterCorePackage* _tmp2_ = NULL;
		AppCenterCorePackage* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp1_ = self->priv->app_version;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp2_ = app_center_abstract_app_container_get_package ((AppCenterAbstractAppContainer*) self);
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp3_ = _tmp2_;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp4_ = app_center_core_package_get_version (_tmp3_);
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_tmp5_ = _tmp4_;
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		gtk_label_set_label (_tmp1_, _tmp5_);
#line 138 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		_g_free0 (_tmp5_);
#line 857 "PackageRow.c"
	}
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_abstract_app_container_update_action ((AppCenterAbstractAppContainer*) self);
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_signal_emit_by_name ((AppCenterWidgetsPackageRowAbstractPackageRowGrid*) self, "changed");
#line 863 "PackageRow.c"
}


static void app_center_widgets_package_row_installed_package_row_grid_real_update_progress_status (AppCenterAbstractAppContainer* base) {
	AppCenterWidgetsPackageRowInstalledPackageRowGrid * self;
	PkStatusEnum status = 0;
	AppCenterCorePackage* _tmp0_ = NULL;
	AppCenterCorePackage* _tmp1_ = NULL;
	AppCenterCoreChangeInformation* _tmp2_ = NULL;
	AppCenterCoreChangeInformation* _tmp3_ = NULL;
	PkStatusEnum _tmp4_ = 0;
	PkStatusEnum _tmp5_ = 0;
	PkStatusEnum _tmp6_ = 0;
#line 145 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowInstalledPackageRowGrid*) base;
#line 146 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	APP_CENTER_ABSTRACT_APP_CONTAINER_CLASS (app_center_widgets_package_row_installed_package_row_grid_parent_class)->update_progress_status ((AppCenterAbstractAppContainer*) G_TYPE_CHECK_INSTANCE_CAST (self, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGrid));
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = app_center_abstract_app_container_get_package ((AppCenterAbstractAppContainer*) self);
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = _tmp0_;
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = app_center_core_package_get_change_information (_tmp1_);
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = _tmp2_;
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = app_center_core_change_information_get_status (_tmp3_);
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = _tmp4_;
#line 147 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	status = _tmp5_;
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp6_ = status;
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	switch (_tmp6_) {
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		case PK_STATUS_ENUM_WAIT:
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		case PK_STATUS_ENUM_FINISHED:
#line 148 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
		case PK_STATUS_ENUM_WAITING_FOR_AUTH:
#line 905 "PackageRow.c"
		{
			GtkProgressBar* _tmp7_ = NULL;
			GtkProgressBar* _tmp8_ = NULL;
#line 152 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			_tmp7_ = ((AppCenterAbstractAppContainer*) self)->progress_bar;
#line 152 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			gtk_widget_set_no_show_all ((GtkWidget*) _tmp7_, TRUE);
#line 153 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			_tmp8_ = ((AppCenterAbstractAppContainer*) self)->progress_bar;
#line 153 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			gtk_widget_hide ((GtkWidget*) _tmp8_);
#line 154 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			break;
#line 919 "PackageRow.c"
		}
		default:
		{
			GtkProgressBar* _tmp9_ = NULL;
			GtkProgressBar* _tmp10_ = NULL;
#line 156 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			_tmp9_ = ((AppCenterAbstractAppContainer*) self)->progress_bar;
#line 156 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			gtk_widget_set_no_show_all ((GtkWidget*) _tmp9_, FALSE);
#line 157 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			_tmp10_ = ((AppCenterAbstractAppContainer*) self)->progress_bar;
#line 157 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			gtk_widget_show_all ((GtkWidget*) _tmp10_);
#line 158 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
			break;
#line 935 "PackageRow.c"
		}
	}
}


static GObject * app_center_widgets_package_row_installed_package_row_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterWidgetsPackageRowInstalledPackageRowGrid * self;
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkStyleContext* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
#line 113 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	parent_class = G_OBJECT_CLASS (app_center_widgets_package_row_installed_package_row_grid_parent_class);
#line 113 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 113 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowInstalledPackageRowGrid);
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainer*) self)->updates_view = TRUE;
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new (NULL);
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_ref_sink (_tmp0_);
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_object_unref0 (self->priv->app_version);
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self->priv->app_version = _tmp0_;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = self->priv->app_version;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) _tmp1_);
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_style_context_add_class (_tmp2_, GTK_STYLE_CLASS_DIM_LABEL);
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = self->priv->app_version;
#line 117 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 118 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = self->priv->app_version;
#line 118 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp4_, GTK_ALIGN_START);
#line 119 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = self->priv->app_version;
#line 119 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_set (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, gtk_misc_get_type (), GtkMisc), "xalign", (gfloat) 0, NULL);
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp6_ = self->priv->app_version;
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp6_, 1, 1, 1, 1);
#line 113 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return obj;
#line 992 "PackageRow.c"
}


static void app_center_widgets_package_row_installed_package_row_grid_class_init (AppCenterWidgetsPackageRowInstalledPackageRowGridClass * klass) {
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_widgets_package_row_installed_package_row_grid_parent_class = g_type_class_peek_parent (klass);
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_type_class_add_private (klass, sizeof (AppCenterWidgetsPackageRowInstalledPackageRowGridPrivate));
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainerClass *) klass)->set_up_package = (void (*)(AppCenterAbstractAppContainer*, guint)) app_center_widgets_package_row_installed_package_row_grid_real_set_up_package;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainerClass *) klass)->update_state = (void (*)(AppCenterAbstractAppContainer*, gboolean)) app_center_widgets_package_row_installed_package_row_grid_real_update_state;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainerClass *) klass)->update_progress_status = (void (*)(AppCenterAbstractAppContainer*)) app_center_widgets_package_row_installed_package_row_grid_real_update_progress_status;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_widgets_package_row_installed_package_row_grid_constructor;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (klass)->finalize = app_center_widgets_package_row_installed_package_row_grid_finalize;
#line 1011 "PackageRow.c"
}


static void app_center_widgets_package_row_installed_package_row_grid_instance_init (AppCenterWidgetsPackageRowInstalledPackageRowGrid * self) {
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self->priv = APP_CENTER_WIDGETS_PACKAGE_ROW_INSTALLED_PACKAGE_ROW_GRID_GET_PRIVATE (self);
#line 1018 "PackageRow.c"
}


static void app_center_widgets_package_row_installed_package_row_grid_finalize (GObject* obj) {
	AppCenterWidgetsPackageRowInstalledPackageRowGrid * self;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_INSTALLED_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowInstalledPackageRowGrid);
#line 111 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_object_unref0 (self->priv->app_version);
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (app_center_widgets_package_row_installed_package_row_grid_parent_class)->finalize (obj);
#line 1030 "PackageRow.c"
}


static GType app_center_widgets_package_row_installed_package_row_grid_get_type (void) {
	static volatile gsize app_center_widgets_package_row_installed_package_row_grid_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_widgets_package_row_installed_package_row_grid_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterWidgetsPackageRowInstalledPackageRowGridClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_widgets_package_row_installed_package_row_grid_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterWidgetsPackageRowInstalledPackageRowGrid), 0, (GInstanceInitFunc) app_center_widgets_package_row_installed_package_row_grid_instance_init, NULL };
		GType app_center_widgets_package_row_installed_package_row_grid_type_id;
		app_center_widgets_package_row_installed_package_row_grid_type_id = g_type_register_static (APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, "AppCenterWidgetsPackageRowInstalledPackageRowGrid", &g_define_type_info, 0);
		g_once_init_leave (&app_center_widgets_package_row_installed_package_row_grid_type_id__volatile, app_center_widgets_package_row_installed_package_row_grid_type_id);
	}
	return app_center_widgets_package_row_installed_package_row_grid_type_id__volatile;
}


static AppCenterWidgetsPackageRowListPackageRowGrid* app_center_widgets_package_row_list_package_row_grid_construct (GType object_type, AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
	AppCenterWidgetsPackageRowListPackageRowGrid * self = NULL;
	AppCenterCorePackage* _tmp0_ = NULL;
	GtkSizeGroup* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_return_val_if_fail (package != NULL, NULL);
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = package;
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = size_group;
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = show_uninstall;
#line 176 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowListPackageRowGrid*) app_center_widgets_package_row_abstract_package_row_grid_construct (object_type, _tmp0_, _tmp1_, _tmp2_);
#line 177 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_abstract_app_container_set_up_package ((AppCenterAbstractAppContainer*) self, (guint) 48);
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return self;
#line 1065 "PackageRow.c"
}


static AppCenterWidgetsPackageRowListPackageRowGrid* app_center_widgets_package_row_list_package_row_grid_new (AppCenterCorePackage* package, GtkSizeGroup* size_group, gboolean show_uninstall) {
#line 175 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return app_center_widgets_package_row_list_package_row_grid_construct (APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID, package, size_group, show_uninstall);
#line 1072 "PackageRow.c"
}


static void app_center_widgets_package_row_list_package_row_grid_real_set_up_package (AppCenterAbstractAppContainer* base, guint icon_size) {
	AppCenterWidgetsPackageRowListPackageRowGrid * self;
	GtkLabel* _tmp0_ = NULL;
	AppCenterCorePackage* _tmp1_ = NULL;
	AppCenterCorePackage* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	guint _tmp6_ = 0U;
#line 180 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = (AppCenterWidgetsPackageRowListPackageRowGrid*) base;
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = app_center_abstract_app_container_get_package ((AppCenterAbstractAppContainer*) self);
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = _tmp1_;
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = app_center_core_package_get_summary (_tmp2_);
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = _tmp3_;
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_label_set_label (_tmp0_, _tmp4_);
#line 181 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_free0 (_tmp4_);
#line 182 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 182 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_label_set_ellipsize (_tmp5_, PANGO_ELLIPSIZE_END);
#line 183 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp6_ = icon_size;
#line 183 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	APP_CENTER_ABSTRACT_APP_CONTAINER_CLASS (app_center_widgets_package_row_list_package_row_grid_parent_class)->set_up_package ((AppCenterAbstractAppContainer*) G_TYPE_CHECK_INSTANCE_CAST (self, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowAbstractPackageRowGrid), _tmp6_);
#line 1109 "PackageRow.c"
}


static GObject * app_center_widgets_package_row_list_package_row_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterWidgetsPackageRowListPackageRowGrid * self;
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkStyleContext* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	parent_class = G_OBJECT_CLASS (app_center_widgets_package_row_list_package_row_grid_parent_class);
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_LIST_PACKAGE_ROW_GRID, AppCenterWidgetsPackageRowListPackageRowGrid);
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp0_ = (GtkLabel*) gtk_label_new (NULL);
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_ref_sink (_tmp0_);
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_object_unref0 (((AppCenterAbstractAppContainer*) self)->package_summary);
#line 166 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainer*) self)->package_summary = _tmp0_;
#line 167 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp1_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 167 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) _tmp1_);
#line 167 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_style_context_add_class (_tmp2_, GTK_STYLE_CLASS_DIM_LABEL);
#line 168 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp3_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 168 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 169 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp4_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 169 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp4_, GTK_ALIGN_START);
#line 170 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp5_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 170 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_object_set (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, gtk_misc_get_type (), GtkMisc), "xalign", (gfloat) 0, NULL);
#line 172 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_tmp6_ = ((AppCenterAbstractAppContainer*) self)->package_summary;
#line 172 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp6_, 1, 1, 1, 1);
#line 165 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	return obj;
#line 1162 "PackageRow.c"
}


static void app_center_widgets_package_row_list_package_row_grid_class_init (AppCenterWidgetsPackageRowListPackageRowGridClass * klass) {
#line 163 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_widgets_package_row_list_package_row_grid_parent_class = g_type_class_peek_parent (klass);
#line 163 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	((AppCenterAbstractAppContainerClass *) klass)->set_up_package = (void (*)(AppCenterAbstractAppContainer*, guint)) app_center_widgets_package_row_list_package_row_grid_real_set_up_package;
#line 163 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_widgets_package_row_list_package_row_grid_constructor;
#line 1173 "PackageRow.c"
}


static void app_center_widgets_package_row_list_package_row_grid_instance_init (AppCenterWidgetsPackageRowListPackageRowGrid * self) {
}


static GType app_center_widgets_package_row_list_package_row_grid_get_type (void) {
	static volatile gsize app_center_widgets_package_row_list_package_row_grid_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_widgets_package_row_list_package_row_grid_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterWidgetsPackageRowListPackageRowGridClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_widgets_package_row_list_package_row_grid_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterWidgetsPackageRowListPackageRowGrid), 0, (GInstanceInitFunc) app_center_widgets_package_row_list_package_row_grid_instance_init, NULL };
		GType app_center_widgets_package_row_list_package_row_grid_type_id;
		app_center_widgets_package_row_list_package_row_grid_type_id = g_type_register_static (APP_CENTER_WIDGETS_PACKAGE_ROW_TYPE_ABSTRACT_PACKAGE_ROW_GRID, "AppCenterWidgetsPackageRowListPackageRowGrid", &g_define_type_info, 0);
		g_once_init_leave (&app_center_widgets_package_row_list_package_row_grid_type_id__volatile, app_center_widgets_package_row_list_package_row_grid_type_id);
	}
	return app_center_widgets_package_row_list_package_row_grid_type_id__volatile;
}


static void app_center_widgets_package_row_class_init (AppCenterWidgetsPackageRowClass * klass) {
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_widgets_package_row_parent_class = g_type_class_peek_parent (klass);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	g_type_class_add_private (klass, sizeof (AppCenterWidgetsPackageRowPrivate));
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (klass)->finalize = app_center_widgets_package_row_finalize;
#line 1200 "PackageRow.c"
}


static void app_center_widgets_package_row_app_center_widgets_app_list_row_interface_init (AppCenterWidgetsAppListRowIface * iface) {
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	app_center_widgets_package_row_app_center_widgets_app_list_row_parent_iface = g_type_interface_peek_parent (iface);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->get_update_available = (gboolean (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_get_update_available;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->get_is_driver = (gboolean (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_get_is_driver;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->get_is_updating = (gboolean (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_get_is_updating;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->get_is_os_updates = (gboolean (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_get_is_os_updates;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->get_name_label = (gchar* (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_get_name_label;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->get_package = (AppCenterCorePackage* (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_get_package;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	iface->has_package = (gboolean (*)(AppCenterWidgetsAppListRow*)) app_center_widgets_package_row_real_has_package;
#line 1221 "PackageRow.c"
}


static void app_center_widgets_package_row_instance_init (AppCenterWidgetsPackageRow * self) {
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self->priv = APP_CENTER_WIDGETS_PACKAGE_ROW_GET_PRIVATE (self);
#line 1228 "PackageRow.c"
}


static void app_center_widgets_package_row_finalize (GObject* obj) {
	AppCenterWidgetsPackageRow * self;
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_TYPE_PACKAGE_ROW, AppCenterWidgetsPackageRow);
#line 23 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	_g_object_unref0 (self->priv->grid);
#line 22 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/PackageRow.vala"
	G_OBJECT_CLASS (app_center_widgets_package_row_parent_class)->finalize (obj);
#line 1240 "PackageRow.c"
}


GType app_center_widgets_package_row_get_type (void) {
	static volatile gsize app_center_widgets_package_row_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_widgets_package_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterWidgetsPackageRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_widgets_package_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterWidgetsPackageRow), 0, (GInstanceInitFunc) app_center_widgets_package_row_instance_init, NULL };
		static const GInterfaceInfo app_center_widgets_app_list_row_info = { (GInterfaceInitFunc) app_center_widgets_package_row_app_center_widgets_app_list_row_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType app_center_widgets_package_row_type_id;
		app_center_widgets_package_row_type_id = g_type_register_static (gtk_list_box_row_get_type (), "AppCenterWidgetsPackageRow", &g_define_type_info, 0);
		g_type_add_interface_static (app_center_widgets_package_row_type_id, APP_CENTER_WIDGETS_TYPE_APP_LIST_ROW, &app_center_widgets_app_list_row_info);
		g_once_init_leave (&app_center_widgets_package_row_type_id__volatile, app_center_widgets_package_row_type_id);
	}
	return app_center_widgets_package_row_type_id__volatile;
}



