/* Switcher.c generated by valac 0.34.8, the Vala compiler
 * generated from Switcher.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/**/
/*  Copyright (C) 2011-2012 Giulio Collura*/
/*  Copyright (C) 2014 Corentin Noël <tintou@mailoo.org>*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define APP_CENTER_WIDGETS_TYPE_SWITCHER (app_center_widgets_switcher_get_type ())
#define APP_CENTER_WIDGETS_SWITCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcher))
#define APP_CENTER_WIDGETS_SWITCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcherClass))
#define APP_CENTER_WIDGETS_IS_SWITCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CENTER_WIDGETS_TYPE_SWITCHER))
#define APP_CENTER_WIDGETS_IS_SWITCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CENTER_WIDGETS_TYPE_SWITCHER))
#define APP_CENTER_WIDGETS_SWITCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcherClass))

typedef struct _AppCenterWidgetsSwitcher AppCenterWidgetsSwitcher;
typedef struct _AppCenterWidgetsSwitcherClass AppCenterWidgetsSwitcherClass;
typedef struct _AppCenterWidgetsSwitcherPrivate AppCenterWidgetsSwitcherPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block29Data Block29Data;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _AppCenterWidgetsSwitcher {
	GtkGrid parent_instance;
	AppCenterWidgetsSwitcherPrivate * priv;
};

struct _AppCenterWidgetsSwitcherClass {
	GtkGridClass parent_class;
};

struct _AppCenterWidgetsSwitcherPrivate {
	GtkStack* stack;
	GeeHashMap* buttons;
};

struct _Block29Data {
	int _ref_count_;
	AppCenterWidgetsSwitcher* self;
	GtkToggleButton* button;
};


static gpointer app_center_widgets_switcher_parent_class = NULL;

GType app_center_widgets_switcher_get_type (void) G_GNUC_CONST;
#define APP_CENTER_WIDGETS_SWITCHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcherPrivate))
enum  {
	APP_CENTER_WIDGETS_SWITCHER_DUMMY_PROPERTY,
	APP_CENTER_WIDGETS_SWITCHER_SIZE
};
#define APP_CENTER_WIDGETS_SWITCHER_SWITCHER_STYLE_CSS "\n" \
"            .switcher {\n" \
"                background-color: transparent;\n" \
"                border: none;\n" \
"                box-shadow: none;\n" \
"                opacity: 0.4;\n" \
"            }\n" \
"\n" \
"            .switcher:checked {\n" \
"                opacity: 1;\n" \
"            }\n" \
"        "
AppCenterWidgetsSwitcher* app_center_widgets_switcher_new (void);
AppCenterWidgetsSwitcher* app_center_widgets_switcher_construct (GType object_type);
void app_center_widgets_switcher_set_stack (AppCenterWidgetsSwitcher* self, GtkStack* stack);
void app_center_widgets_switcher_clear_children (AppCenterWidgetsSwitcher* self);
static void app_center_widgets_switcher_populate_switcher (AppCenterWidgetsSwitcher* self);
static void app_center_widgets_switcher_connect_stack_signals (AppCenterWidgetsSwitcher* self);
void app_center_widgets_switcher_update_selected (AppCenterWidgetsSwitcher* self);
static void app_center_widgets_switcher_add_child (AppCenterWidgetsSwitcher* self, GtkWidget* widget);
static Block29Data* block29_data_ref (Block29Data* _data29_);
static void block29_data_unref (void * _userdata_);
static gboolean __lambda72_ (Block29Data* _data29_);
static void app_center_widgets_switcher_on_button_clicked (AppCenterWidgetsSwitcher* self, GtkWidget* widget);
static gboolean ___lambda72__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void app_center_widgets_switcher_real_show (GtkWidget* base);
static void app_center_widgets_switcher_real_show_all (GtkWidget* base);
static void app_center_widgets_switcher_on_stack_child_removed (AppCenterWidgetsSwitcher* self, GtkWidget* widget);
static void _app_center_widgets_switcher_add_child_gtk_container_add (GtkContainer* _sender, GtkWidget* widget, gpointer self);
static void _app_center_widgets_switcher_on_stack_child_removed_gtk_container_remove (GtkContainer* _sender, GtkWidget* widget, gpointer self);
gint app_center_widgets_switcher_get_size (AppCenterWidgetsSwitcher* self);
static GObject * app_center_widgets_switcher_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void app_center_widgets_switcher_finalize (GObject* obj);
static void _vala_app_center_widgets_switcher_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


AppCenterWidgetsSwitcher* app_center_widgets_switcher_construct (GType object_type) {
	AppCenterWidgetsSwitcher * self = NULL;
	GeeHashMap* _tmp0_ = NULL;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self = (AppCenterWidgetsSwitcher*) g_object_new (object_type, NULL);
#line 47 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_grid_set_column_spacing ((GtkGrid*) self, 3);
#line 48 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_object_set ((GtkWidget*) self, "can-focus", FALSE, NULL);
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = gee_hash_map_new (gtk_widget_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, gtk_toggle_button_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (self->priv->buttons);
#line 49 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self->priv->buttons = _tmp0_;
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return self;
#line 119 "Switcher.c"
}


AppCenterWidgetsSwitcher* app_center_widgets_switcher_new (void) {
#line 46 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return app_center_widgets_switcher_construct (APP_CENTER_WIDGETS_TYPE_SWITCHER);
#line 126 "Switcher.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return self ? g_object_ref (self) : NULL;
#line 133 "Switcher.c"
}


void app_center_widgets_switcher_set_stack (AppCenterWidgetsSwitcher* self, GtkStack* stack) {
	GtkStack* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkStack* _tmp2_ = NULL;
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 62 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (stack != NULL);
#line 63 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->stack;
#line 63 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	if (_tmp0_ != NULL) {
#line 64 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		app_center_widgets_switcher_clear_children (self);
#line 151 "Switcher.c"
	}
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = stack;
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (self->priv->stack);
#line 66 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self->priv->stack = _tmp2_;
#line 67 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	app_center_widgets_switcher_populate_switcher (self);
#line 68 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	app_center_widgets_switcher_connect_stack_signals (self);
#line 69 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	app_center_widgets_switcher_update_selected (self);
#line 167 "Switcher.c"
}


static Block29Data* block29_data_ref (Block29Data* _data29_) {
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_atomic_int_inc (&_data29_->_ref_count_);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return _data29_;
#line 176 "Switcher.c"
}


static void block29_data_unref (void * _userdata_) {
	Block29Data* _data29_;
	_data29_ = (Block29Data*) _userdata_;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	if (g_atomic_int_dec_and_test (&_data29_->_ref_count_)) {
#line 185 "Switcher.c"
		AppCenterWidgetsSwitcher* self;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		self = _data29_->self;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (_data29_->button);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (self);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		g_slice_free (Block29Data, _data29_);
#line 195 "Switcher.c"
	}
}


static gboolean __lambda72_ (Block29Data* _data29_) {
	AppCenterWidgetsSwitcher* self;
	gboolean result = FALSE;
	GtkToggleButton* _tmp20_ = NULL;
#line 77 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self = _data29_->self;
#line 206 "Switcher.c"
	{
		GeeIterator* _entry_it = NULL;
		GeeHashMap* _tmp0_ = NULL;
		GeeSet* _tmp1_ = NULL;
		GeeSet* _tmp2_ = NULL;
		GeeSet* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		GeeIterator* _tmp5_ = NULL;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp0_ = self->priv->buttons;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp1_ = gee_abstract_map_get_entries ((GeeAbstractMap*) _tmp0_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp2_ = _tmp1_;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp3_ = _tmp2_;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp4_ = gee_iterable_iterator ((GeeIterable*) _tmp3_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp5_ = _tmp4_;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (_tmp3_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_entry_it = _tmp5_;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		while (TRUE) {
#line 233 "Switcher.c"
			GeeIterator* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			GeeMapEntry* entry = NULL;
			GeeIterator* _tmp8_ = NULL;
			gpointer _tmp9_ = NULL;
			GeeMapEntry* _tmp10_ = NULL;
			gconstpointer _tmp11_ = NULL;
			GtkToggleButton* _tmp12_ = NULL;
			GtkToggleButton* _tmp13_ = NULL;
			GeeMapEntry* _tmp17_ = NULL;
			gconstpointer _tmp18_ = NULL;
			GtkToggleButton* _tmp19_ = NULL;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp6_ = _entry_it;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp7_ = gee_iterator_next (_tmp6_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			if (!_tmp7_) {
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				break;
#line 254 "Switcher.c"
			}
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp8_ = _entry_it;
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp9_ = gee_iterator_get (_tmp8_);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			entry = (GeeMapEntry*) _tmp9_;
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp10_ = entry;
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp11_ = gee_map_entry_get_value (_tmp10_);
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp12_ = _tmp11_;
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp13_ = _data29_->button;
#line 79 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			if (((GtkToggleButton*) _tmp12_) == _tmp13_) {
#line 272 "Switcher.c"
				GeeMapEntry* _tmp14_ = NULL;
				gconstpointer _tmp15_ = NULL;
				GtkWidget* _tmp16_ = NULL;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp14_ = entry;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp15_ = gee_map_entry_get_key (_tmp14_);
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp16_ = _tmp15_;
#line 80 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				app_center_widgets_switcher_on_button_clicked (self, (GtkWidget*) _tmp16_);
#line 284 "Switcher.c"
			}
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp17_ = entry;
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp18_ = gee_map_entry_get_value (_tmp17_);
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp19_ = _tmp18_;
#line 81 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			gtk_toggle_button_set_active ((GtkToggleButton*) _tmp19_, FALSE);
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_g_object_unref0 (entry);
#line 296 "Switcher.c"
		}
#line 78 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (_entry_it);
#line 300 "Switcher.c"
	}
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp20_ = _data29_->button;
#line 83 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_toggle_button_set_active (_tmp20_, TRUE);
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	result = TRUE;
#line 84 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return result;
#line 310 "Switcher.c"
}


static gboolean ___lambda72__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda72_ (self);
#line 77 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return result;
#line 319 "Switcher.c"
}


static void app_center_widgets_switcher_add_child (AppCenterWidgetsSwitcher* self, GtkWidget* widget) {
	Block29Data* _data29_;
	GtkToggleButton* _tmp0_ = NULL;
	GtkToggleButton* _tmp1_ = NULL;
	GtkImage* _tmp2_ = NULL;
	GtkImage* _tmp3_ = NULL;
	GtkToggleButton* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_ = NULL;
	GtkToggleButton* _tmp6_ = NULL;
	GtkStyleContext* _tmp7_ = NULL;
	GtkToggleButton* _tmp8_ = NULL;
	GtkToggleButton* _tmp9_ = NULL;
	GeeHashMap* _tmp10_ = NULL;
	GtkWidget* _tmp11_ = NULL;
	GtkToggleButton* _tmp12_ = NULL;
	GeeHashMap* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (widget != NULL);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_data29_ = g_slice_new0 (Block29Data);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_data29_->_ref_count_ = 1;
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_data29_->self = g_object_ref (self);
#line 73 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = (GtkToggleButton*) gtk_toggle_button_new ();
#line 73 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_object_ref_sink (_tmp0_);
#line 73 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_data29_->button = _tmp0_;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = _data29_->button;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp2_ = (GtkImage*) gtk_image_new_from_icon_name ("pager-checked-symbolic", GTK_ICON_SIZE_MENU);
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_object_ref_sink (_tmp2_);
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp3_ = _tmp2_;
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_button_set_image ((GtkButton*) _tmp1_, (GtkWidget*) _tmp3_);
#line 74 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (_tmp3_);
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp4_ = _data29_->button;
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 75 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_style_context_add_class (_tmp5_, GTK_STYLE_CLASS_FLAT);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp6_ = _data29_->button;
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) _tmp6_);
#line 76 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_style_context_add_class (_tmp7_, "switcher");
#line 77 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp8_ = _data29_->button;
#line 77 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_signal_connect_data ((GtkWidget*) _tmp8_, "button-release-event", (GCallback) ___lambda72__gtk_widget_button_release_event, block29_data_ref (_data29_), (GClosureNotify) block29_data_unref, 0);
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp9_ = _data29_->button;
#line 87 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp9_);
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp10_ = self->priv->buttons;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp11_ = widget;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp12_ = _data29_->button;
#line 88 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp10_, _tmp11_, _tmp12_);
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp13_ = self->priv->buttons;
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp14_ = gee_abstract_map_get_size ((GeeAbstractMap*) _tmp13_);
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp15_ = _tmp14_;
#line 89 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	if (_tmp15_ == 1) {
#line 405 "Switcher.c"
		GtkToggleButton* _tmp16_ = NULL;
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp16_ = _data29_->button;
#line 90 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		gtk_toggle_button_set_active (_tmp16_, TRUE);
#line 411 "Switcher.c"
	}
#line 93 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	block29_data_unref (_data29_);
#line 72 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_data29_ = NULL;
#line 419 "Switcher.c"
}


static void app_center_widgets_switcher_real_show (GtkWidget* base) {
	AppCenterWidgetsSwitcher * self;
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 96 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self = (AppCenterWidgetsSwitcher*) base;
#line 97 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	GTK_WIDGET_CLASS (app_center_widgets_switcher_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_grid_get_type (), GtkGrid));
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->buttons;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = gee_abstract_map_get_size ((GeeAbstractMap*) _tmp0_);
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp2_ = _tmp1_;
#line 98 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	if (_tmp2_ <= 1) {
#line 99 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		gtk_widget_hide ((GtkWidget*) self);
#line 442 "Switcher.c"
	}
}


static void app_center_widgets_switcher_real_show_all (GtkWidget* base) {
	AppCenterWidgetsSwitcher * self;
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 103 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self = (AppCenterWidgetsSwitcher*) base;
#line 104 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	GTK_WIDGET_CLASS (app_center_widgets_switcher_parent_class)->show_all ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_grid_get_type (), GtkGrid));
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->buttons;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = gee_abstract_map_get_size ((GeeAbstractMap*) _tmp0_);
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp2_ = _tmp1_;
#line 105 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	if (_tmp2_ <= 1) {
#line 106 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		gtk_widget_hide ((GtkWidget*) self);
#line 466 "Switcher.c"
	}
}


static void app_center_widgets_switcher_on_button_clicked (AppCenterWidgetsSwitcher* self, GtkWidget* widget) {
	GtkStack* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
#line 109 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 109 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (widget != NULL);
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->stack;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = widget;
#line 110 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_stack_set_visible_child (_tmp0_, _tmp1_);
#line 111 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_signal_emit_by_name (self, "on-stack-changed");
#line 486 "Switcher.c"
}


static void app_center_widgets_switcher_populate_switcher (AppCenterWidgetsSwitcher* self) {
	GtkStack* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
#line 114 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->stack;
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
#line 499 "Switcher.c"
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		child_collection = _tmp1_;
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
#line 507 "Switcher.c"
			GtkWidget* child = NULL;
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			child = (GtkWidget*) child_it->data;
#line 511 "Switcher.c"
			{
				GtkWidget* _tmp2_ = NULL;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp2_ = child;
#line 116 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				app_center_widgets_switcher_add_child (self, _tmp2_);
#line 518 "Switcher.c"
			}
		}
#line 115 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_list_free0 (child_collection);
#line 523 "Switcher.c"
	}
}


static void app_center_widgets_switcher_on_stack_child_removed (AppCenterWidgetsSwitcher* self, GtkWidget* widget) {
	GtkToggleButton* button = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	GtkWidget* _tmp4_ = NULL;
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (widget != NULL);
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->buttons;
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = widget;
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 121 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	button = (GtkToggleButton*) _tmp2_;
#line 122 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gtk_container_remove ((GtkContainer*) self, (GtkWidget*) button);
#line 123 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp3_ = self->priv->buttons;
#line 123 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp4_ = widget;
#line 123 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp3_, _tmp4_, NULL);
#line 120 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (button);
#line 557 "Switcher.c"
}


static void _app_center_widgets_switcher_add_child_gtk_container_add (GtkContainer* _sender, GtkWidget* widget, gpointer self) {
#line 127 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	app_center_widgets_switcher_add_child ((AppCenterWidgetsSwitcher*) self, widget);
#line 564 "Switcher.c"
}


static void _app_center_widgets_switcher_on_stack_child_removed_gtk_container_remove (GtkContainer* _sender, GtkWidget* widget, gpointer self) {
#line 128 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	app_center_widgets_switcher_on_stack_child_removed ((AppCenterWidgetsSwitcher*) self, widget);
#line 571 "Switcher.c"
}


static void app_center_widgets_switcher_connect_stack_signals (AppCenterWidgetsSwitcher* self) {
	GtkStack* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
#line 126 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 127 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->stack;
#line 127 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_signal_connect_object ((GtkContainer*) _tmp0_, "add", (GCallback) _app_center_widgets_switcher_add_child_gtk_container_add, self, G_CONNECT_AFTER);
#line 128 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = self->priv->stack;
#line 128 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_signal_connect_object ((GtkContainer*) _tmp1_, "remove", (GCallback) _app_center_widgets_switcher_on_stack_child_removed_gtk_container_remove, self, G_CONNECT_AFTER);
#line 588 "Switcher.c"
}


void app_center_widgets_switcher_clear_children (AppCenterWidgetsSwitcher* self) {
	GList* _tmp0_ = NULL;
#line 131 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 598 "Switcher.c"
	{
		GList* button_collection = NULL;
		GList* button_it = NULL;
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		button_collection = _tmp0_;
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		for (button_it = button_collection; button_it != NULL; button_it = button_it->next) {
#line 606 "Switcher.c"
			GtkWidget* button = NULL;
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			button = (GtkWidget*) button_it->data;
#line 610 "Switcher.c"
			{
				GtkWidget* _tmp1_ = NULL;
				GtkWidget* _tmp2_ = NULL;
				GtkContainer* _tmp3_ = NULL;
#line 133 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp1_ = button;
#line 133 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				gtk_widget_hide (_tmp1_);
#line 134 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp2_ = button;
#line 134 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp3_ = (GtkContainer*) gtk_widget_get_parent (_tmp2_);
#line 134 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				if (_tmp3_ != NULL) {
#line 625 "Switcher.c"
					GtkWidget* _tmp4_ = NULL;
#line 135 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
					_tmp4_ = button;
#line 135 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
					gtk_container_remove ((GtkContainer*) self, _tmp4_);
#line 631 "Switcher.c"
				}
			}
		}
#line 132 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_list_free0 (button_collection);
#line 637 "Switcher.c"
	}
}


void app_center_widgets_switcher_update_selected (AppCenterWidgetsSwitcher* self) {
#line 139 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_if_fail (self != NULL);
#line 645 "Switcher.c"
	{
		GeeIterator* _entry_it = NULL;
		GeeHashMap* _tmp0_ = NULL;
		GeeSet* _tmp1_ = NULL;
		GeeSet* _tmp2_ = NULL;
		GeeSet* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		GeeIterator* _tmp5_ = NULL;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp0_ = self->priv->buttons;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp1_ = gee_abstract_map_get_entries ((GeeAbstractMap*) _tmp0_);
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp2_ = _tmp1_;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp3_ = _tmp2_;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp4_ = gee_iterable_iterator ((GeeIterable*) _tmp3_);
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp5_ = _tmp4_;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (_tmp3_);
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_entry_it = _tmp5_;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		while (TRUE) {
#line 672 "Switcher.c"
			GeeIterator* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			GeeMapEntry* entry = NULL;
			GeeIterator* _tmp8_ = NULL;
			gpointer _tmp9_ = NULL;
			GeeMapEntry* _tmp10_ = NULL;
			gconstpointer _tmp11_ = NULL;
			GtkWidget* _tmp12_ = NULL;
			GtkStack* _tmp13_ = NULL;
			GtkWidget* _tmp14_ = NULL;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp6_ = _entry_it;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp7_ = gee_iterator_next (_tmp6_);
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			if (!_tmp7_) {
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				break;
#line 691 "Switcher.c"
			}
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp8_ = _entry_it;
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp9_ = gee_iterator_get (_tmp8_);
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			entry = (GeeMapEntry*) _tmp9_;
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp10_ = entry;
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp11_ = gee_map_entry_get_key (_tmp10_);
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp12_ = _tmp11_;
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp13_ = self->priv->stack;
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_tmp14_ = gtk_stack_get_visible_child (_tmp13_);
#line 141 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			if (((GtkWidget*) _tmp12_) == _tmp14_) {
#line 711 "Switcher.c"
				GeeMapEntry* _tmp15_ = NULL;
				gconstpointer _tmp16_ = NULL;
				GtkToggleButton* _tmp17_ = NULL;
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp15_ = entry;
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp16_ = gee_map_entry_get_value (_tmp15_);
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp17_ = _tmp16_;
#line 142 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				gtk_toggle_button_set_active ((GtkToggleButton*) _tmp17_, TRUE);
#line 723 "Switcher.c"
			} else {
				GeeMapEntry* _tmp18_ = NULL;
				gconstpointer _tmp19_ = NULL;
				GtkToggleButton* _tmp20_ = NULL;
#line 144 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp18_ = entry;
#line 144 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp19_ = gee_map_entry_get_value (_tmp18_);
#line 144 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				_tmp20_ = _tmp19_;
#line 144 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
				gtk_toggle_button_set_active ((GtkToggleButton*) _tmp20_, FALSE);
#line 736 "Switcher.c"
			}
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
			_g_object_unref0 (entry);
#line 740 "Switcher.c"
		}
#line 140 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (_entry_it);
#line 744 "Switcher.c"
	}
}


gint app_center_widgets_switcher_get_size (AppCenterWidgetsSwitcher* self) {
	gint result;
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 37 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = self->priv->buttons;
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp1_ = gee_abstract_map_get_size ((GeeAbstractMap*) _tmp0_);
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp2_ = _tmp1_;
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	result = (gint) _tmp2_;
#line 38 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return result;
#line 766 "Switcher.c"
}


static GObject * app_center_widgets_switcher_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	AppCenterWidgetsSwitcher * self;
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	parent_class = G_OBJECT_CLASS (app_center_widgets_switcher_parent_class);
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcher);
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_tmp0_ = gtk_css_provider_new ();
#line 53 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	provider = _tmp0_;
#line 787 "Switcher.c"
	{
		GtkCssProvider* _tmp1_ = NULL;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		GdkScreen* _tmp4_ = NULL;
		GtkCssProvider* _tmp5_ = NULL;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp1_ = provider;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp2_ = strlen (APP_CENTER_WIDGETS_SWITCHER_SWITCHER_STYLE_CSS);
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp3_ = _tmp2_;
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		gtk_css_provider_load_from_data (_tmp1_, APP_CENTER_WIDGETS_SWITCHER_SWITCHER_STYLE_CSS, (gssize) _tmp3_, &_inner_error_);
#line 55 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 804 "Switcher.c"
			goto __catch39_g_error;
		}
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp4_ = gdk_screen_get_default ();
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp5_ = provider;
#line 56 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		gtk_style_context_add_provider_for_screen (_tmp4_, (GtkStyleProvider*) _tmp5_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 813 "Switcher.c"
	}
	goto __finally39;
	__catch39_g_error:
	{
		GError* e = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		e = _inner_error_;
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_inner_error_ = NULL;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp6_ = e;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_tmp7_ = _tmp6_->message;
#line 58 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		g_critical ("Switcher.vala:58: %s", _tmp7_);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_error_free0 (e);
#line 833 "Switcher.c"
	}
	__finally39:
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		_g_object_unref0 (provider);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 54 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		g_clear_error (&_inner_error_);
#line 844 "Switcher.c"
	}
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (provider);
#line 52 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	return obj;
#line 850 "Switcher.c"
}


static void app_center_widgets_switcher_class_init (AppCenterWidgetsSwitcherClass * klass) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	app_center_widgets_switcher_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_type_class_add_private (klass, sizeof (AppCenterWidgetsSwitcherPrivate));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	((GtkWidgetClass *) klass)->show = (void (*)(GtkWidget*)) app_center_widgets_switcher_real_show;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	((GtkWidgetClass *) klass)->show_all = (void (*)(GtkWidget*)) app_center_widgets_switcher_real_show_all;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_app_center_widgets_switcher_get_property;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	G_OBJECT_CLASS (klass)->constructor = app_center_widgets_switcher_constructor;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	G_OBJECT_CLASS (klass)->finalize = app_center_widgets_switcher_finalize;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CENTER_WIDGETS_SWITCHER_SIZE, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	g_signal_new ("on_stack_changed", APP_CENTER_WIDGETS_TYPE_SWITCHER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 873 "Switcher.c"
}


static void app_center_widgets_switcher_instance_init (AppCenterWidgetsSwitcher * self) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self->priv = APP_CENTER_WIDGETS_SWITCHER_GET_PRIVATE (self);
#line 880 "Switcher.c"
}


static void app_center_widgets_switcher_finalize (GObject* obj) {
	AppCenterWidgetsSwitcher * self;
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcher);
#line 42 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (self->priv->stack);
#line 43 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	_g_object_unref0 (self->priv->buttons);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	G_OBJECT_CLASS (app_center_widgets_switcher_parent_class)->finalize (obj);
#line 894 "Switcher.c"
}


GType app_center_widgets_switcher_get_type (void) {
	static volatile gsize app_center_widgets_switcher_type_id__volatile = 0;
	if (g_once_init_enter (&app_center_widgets_switcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppCenterWidgetsSwitcherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_center_widgets_switcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppCenterWidgetsSwitcher), 0, (GInstanceInitFunc) app_center_widgets_switcher_instance_init, NULL };
		GType app_center_widgets_switcher_type_id;
		app_center_widgets_switcher_type_id = g_type_register_static (gtk_grid_get_type (), "AppCenterWidgetsSwitcher", &g_define_type_info, 0);
		g_once_init_leave (&app_center_widgets_switcher_type_id__volatile, app_center_widgets_switcher_type_id);
	}
	return app_center_widgets_switcher_type_id__volatile;
}


static void _vala_app_center_widgets_switcher_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	AppCenterWidgetsSwitcher * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_CENTER_WIDGETS_TYPE_SWITCHER, AppCenterWidgetsSwitcher);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
	switch (property_id) {
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		case APP_CENTER_WIDGETS_SWITCHER_SIZE:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		g_value_set_int (value, app_center_widgets_switcher_get_size (self));
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		break;
#line 921 "Switcher.c"
		default:
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "/home/kedarbrooks/Documents/Projects/AppStore/src/Widgets/Switcher.vala"
		break;
#line 927 "Switcher.c"
	}
}



